// This is automatically generated by CodeBind. Please do not modify it.

namespace SpaceShooter.UI
{
    public partial class UIHomeForm
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_AboutButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_AboutTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_AboutmaskButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_PlayGameButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_logoImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_titleText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_versionText;


        public UnityEngine.UI.Button AboutButton => m_AboutButton;
        public UnityEngine.Transform AboutTransform => m_AboutTransform;
        public UnityEngine.UI.Button AboutmaskButton => m_AboutmaskButton;
        public UnityEngine.UI.Button PlayGameButton => m_PlayGameButton;
        public UnityEngine.UI.Image logoImage => m_logoImage;
        public UnityEngine.UI.Text titleText => m_titleText;
        public UnityEngine.UI.Text versionText => m_versionText;


    }
}
