// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class AboutForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.ExButton BackButtonExButton { get; private set; }
        public UnityEngine.RectTransform ContentRectTransform { get; private set; }
        public UnityEngine.UI.Text DescriptionText { get; private set; }
        public UnityEngine.UI.Text IntroductionText { get; private set; }
        public UnityEngine.UI.Text SummaryText { get; private set; }
        public UnityEngine.UI.Text TitleText { get; private set; }
        public UnityEngine.UI.Image UnityLogoImage { get; private set; }
        public UnityEngine.UI.Text WebsiteText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            BackButtonExButton = Mono.BindComponents[0] as Game.ExButton;
            ContentRectTransform = Mono.BindComponents[1] as UnityEngine.RectTransform;
            DescriptionText = Mono.BindComponents[2] as UnityEngine.UI.Text;
            IntroductionText = Mono.BindComponents[3] as UnityEngine.UI.Text;
            SummaryText = Mono.BindComponents[4] as UnityEngine.UI.Text;
            TitleText = Mono.BindComponents[5] as UnityEngine.UI.Text;
            UnityLogoImage = Mono.BindComponents[6] as UnityEngine.UI.Image;
            WebsiteText = Mono.BindComponents[7] as UnityEngine.UI.Text;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            BackButtonExButton = null;
            ContentRectTransform = null;
            DescriptionText = null;
            IntroductionText = null;
            SummaryText = null;
            TitleText = null;
            UnityLogoImage = null;
            WebsiteText = null;
        }
    }
}
