// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class DialogForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public UnityEngine.Transform ButtonGroup1Transform { get; private set; }
        public UnityEngine.Transform ButtonGroup2Transform { get; private set; }
        public UnityEngine.Transform ButtonGroup3Transform { get; private set; }
        public Game.ExButton Group1ConfirmExButton { get; private set; }
        public UnityEngine.UI.Text Group1ConfirmText { get; private set; }
        public UnityEngine.UI.Image Group1ConfirmBorderImage { get; private set; }
        public Game.ExButton Group2CancelExButton { get; private set; }
        public UnityEngine.UI.Text Group2CancelText { get; private set; }
        public UnityEngine.UI.Image Group2CancelBorderImage { get; private set; }
        public Game.ExButton Group2ConfirmExButton { get; private set; }
        public UnityEngine.UI.Text Group2ConfirmText { get; private set; }
        public UnityEngine.UI.Image Group2ConfirmBorderImage { get; private set; }
        public Game.ExButton Group3CancelExButton { get; private set; }
        public UnityEngine.UI.Text Group3CancelText { get; private set; }
        public UnityEngine.UI.Image Group3CancelBorderImage { get; private set; }
        public Game.ExButton Group3ConfirmExButton { get; private set; }
        public UnityEngine.UI.Text Group3ConfirmText { get; private set; }
        public UnityEngine.UI.Image Group3ConfirmBorderImage { get; private set; }
        public Game.ExButton Group3OtherExButton { get; private set; }
        public UnityEngine.UI.Text MessageText { get; private set; }
        public UnityEngine.UI.Text OtherTextText { get; private set; }
        public UnityEngine.UI.Text TitleText { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            ButtonGroup1Transform = Mono.BindComponents[0] as UnityEngine.Transform;
            ButtonGroup2Transform = Mono.BindComponents[1] as UnityEngine.Transform;
            ButtonGroup3Transform = Mono.BindComponents[2] as UnityEngine.Transform;
            Group1ConfirmExButton = Mono.BindComponents[3] as Game.ExButton;
            Group1ConfirmText = Mono.BindComponents[4] as UnityEngine.UI.Text;
            Group1ConfirmBorderImage = Mono.BindComponents[5] as UnityEngine.UI.Image;
            Group2CancelExButton = Mono.BindComponents[6] as Game.ExButton;
            Group2CancelText = Mono.BindComponents[7] as UnityEngine.UI.Text;
            Group2CancelBorderImage = Mono.BindComponents[8] as UnityEngine.UI.Image;
            Group2ConfirmExButton = Mono.BindComponents[9] as Game.ExButton;
            Group2ConfirmText = Mono.BindComponents[10] as UnityEngine.UI.Text;
            Group2ConfirmBorderImage = Mono.BindComponents[11] as UnityEngine.UI.Image;
            Group3CancelExButton = Mono.BindComponents[12] as Game.ExButton;
            Group3CancelText = Mono.BindComponents[13] as UnityEngine.UI.Text;
            Group3CancelBorderImage = Mono.BindComponents[14] as UnityEngine.UI.Image;
            Group3ConfirmExButton = Mono.BindComponents[15] as Game.ExButton;
            Group3ConfirmText = Mono.BindComponents[16] as UnityEngine.UI.Text;
            Group3ConfirmBorderImage = Mono.BindComponents[17] as UnityEngine.UI.Image;
            Group3OtherExButton = Mono.BindComponents[18] as Game.ExButton;
            MessageText = Mono.BindComponents[19] as UnityEngine.UI.Text;
            OtherTextText = Mono.BindComponents[20] as UnityEngine.UI.Text;
            TitleText = Mono.BindComponents[21] as UnityEngine.UI.Text;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            ButtonGroup1Transform = null;
            ButtonGroup2Transform = null;
            ButtonGroup3Transform = null;
            Group1ConfirmExButton = null;
            Group1ConfirmText = null;
            Group1ConfirmBorderImage = null;
            Group2CancelExButton = null;
            Group2CancelText = null;
            Group2CancelBorderImage = null;
            Group2ConfirmExButton = null;
            Group2ConfirmText = null;
            Group2ConfirmBorderImage = null;
            Group3CancelExButton = null;
            Group3CancelText = null;
            Group3CancelBorderImage = null;
            Group3ConfirmExButton = null;
            Group3ConfirmText = null;
            Group3ConfirmBorderImage = null;
            Group3OtherExButton = null;
            MessageText = null;
            OtherTextText = null;
            TitleText = null;
        }
    }
}
