// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class MenuForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.ExButton AboutExButton { get; private set; }
        public Game.ExButton QuitExButton { get; private set; }
        public Game.ExButton SettingExButton { get; private set; }
        public Game.ExButton StartExButton { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            AboutExButton = Mono.BindComponents[0] as Game.ExButton;
            QuitExButton = Mono.BindComponents[1] as Game.ExButton;
            SettingExButton = Mono.BindComponents[2] as Game.ExButton;
            StartExButton = Mono.BindComponents[3] as Game.ExButton;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            AboutExButton = null;
            QuitExButton = null;
            SettingExButton = null;
            StartExButton = null;
        }
    }
}
