// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class SettingForm : CodeBind.ICSCodeBind
    {
        public CodeBind.CSCodeBindMono Mono { get; private set; }
        public UnityEngine.Transform Transform { get; private set; }

        public Game.Hot.CommonButton CancelCommonButton { get; private set; }
        public UnityEngine.UI.Toggle ChineseSimplifiedToggle { get; private set; }
        public UnityEngine.UI.Toggle ChineseTraditionalToggle { get; private set; }
        public Game.Hot.CommonButton ConfirmCommonButton { get; private set; }
        public UnityEngine.UI.Toggle EnglishToggle { get; private set; }
        public UnityEngine.UI.Toggle KoreanToggle { get; private set; }
        public UnityEngine.CanvasGroup LanguageTipsCanvasGroup { get; private set; }
        public UnityEngine.UI.Toggle MusicMuteToggle { get; private set; }
        public UnityEngine.UI.Slider MusicVolumeSlider { get; private set; }
        public UnityEngine.UI.Toggle SoundMuteToggle { get; private set; }
        public UnityEngine.UI.Slider SoundVolumeSlider { get; private set; }
        public UnityEngine.UI.Toggle UISoundMuteToggle { get; private set; }
        public UnityEngine.UI.Slider UISoundVolumeSlider { get; private set; }


        public void InitBind(CodeBind.CSCodeBindMono mono)
        {
            Mono = mono;
            Transform = mono.transform;
            CancelCommonButton = Mono.BindComponents[0] as Game.Hot.CommonButton;
            ChineseSimplifiedToggle = Mono.BindComponents[1] as UnityEngine.UI.Toggle;
            ChineseTraditionalToggle = Mono.BindComponents[2] as UnityEngine.UI.Toggle;
            ConfirmCommonButton = Mono.BindComponents[3] as Game.Hot.CommonButton;
            EnglishToggle = Mono.BindComponents[4] as UnityEngine.UI.Toggle;
            KoreanToggle = Mono.BindComponents[5] as UnityEngine.UI.Toggle;
            LanguageTipsCanvasGroup = Mono.BindComponents[6] as UnityEngine.CanvasGroup;
            MusicMuteToggle = Mono.BindComponents[7] as UnityEngine.UI.Toggle;
            MusicVolumeSlider = Mono.BindComponents[8] as UnityEngine.UI.Slider;
            SoundMuteToggle = Mono.BindComponents[9] as UnityEngine.UI.Toggle;
            SoundVolumeSlider = Mono.BindComponents[10] as UnityEngine.UI.Slider;
            UISoundMuteToggle = Mono.BindComponents[11] as UnityEngine.UI.Toggle;
            UISoundVolumeSlider = Mono.BindComponents[12] as UnityEngine.UI.Slider;
        }

        public void ClearBind()
        {
            Mono = null;
            Transform = null;
            CancelCommonButton = null;
            ChineseSimplifiedToggle = null;
            ChineseTraditionalToggle = null;
            ConfirmCommonButton = null;
            EnglishToggle = null;
            KoreanToggle = null;
            LanguageTipsCanvasGroup = null;
            MusicMuteToggle = null;
            MusicVolumeSlider = null;
            SoundMuteToggle = null;
            SoundVolumeSlider = null;
            UISoundMuteToggle = null;
            UISoundVolumeSlider = null;
        }
    }
}
