
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    public enum BulletType
    {
        /// <summary>
        /// Linear movement
        /// </summary>
        Linear = 0,
        /// <summary>
        /// Curve movement
        /// </summary>
        Curve = 1,
        /// <summary>
        /// Seeking movement
        /// </summary>
        Seeking = 2,
    }

} 

