
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// merchant offer slot constraint
/// </summary>
public partial struct BuqiMerchantSlotConfig
{
    public BuqiMerchantSlotConfig(ByteBuf _buf) 
    {
        SlotId = _buf.ReadString();
        SlotKind = (BuqiMerchantSlotKind)_buf.ReadInt();
        BuildFilter = _buf.ReadString();
        SizeFilter = _buf.ReadString();
        QualityFilter = _buf.ReadString();
        RequiredTag = _buf.ReadString();
        MinUnlockDay = _buf.ReadInt();
        MaxUnlockDay = _buf.ReadInt();
        Weight = _buf.ReadInt();
        Count = _buf.ReadInt();
        PostInit();
    }

    public static BuqiMerchantSlotConfig DeserializeBuqiMerchantSlotConfig(ByteBuf _buf)
    {
        return new BuqiMerchantSlotConfig(_buf);
    }

    /// <summary>
    /// slot id
    /// </summary>
    public readonly string SlotId;
    /// <summary>
    /// slot kind
    /// </summary>
    public readonly BuqiMerchantSlotKind SlotKind;
    /// <summary>
    /// plus separated builds
    /// </summary>
    public readonly string BuildFilter;
    /// <summary>
    /// plus separated sizes
    /// </summary>
    public readonly string SizeFilter;
    /// <summary>
    /// plus separated qualities
    /// </summary>
    public readonly string QualityFilter;
    /// <summary>
    /// required tag
    /// </summary>
    public readonly string RequiredTag;
    /// <summary>
    /// minimum item unlock day
    /// </summary>
    public readonly int MinUnlockDay;
    /// <summary>
    /// maximum item unlock day
    /// </summary>
    public readonly int MaxUnlockDay;
    /// <summary>
    /// slot weight
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// offer count
    /// </summary>
    public readonly int Count;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "SlotId:" + SlotId + ","
        + "SlotKind:" + SlotKind + ","
        + "BuildFilter:" + BuildFilter + ","
        + "SizeFilter:" + SizeFilter + ","
        + "QualityFilter:" + QualityFilter + ","
        + "RequiredTag:" + RequiredTag + ","
        + "MinUnlockDay:" + MinUnlockDay + ","
        + "MaxUnlockDay:" + MaxUnlockDay + ","
        + "Weight:" + Weight + ","
        + "Count:" + Count + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
