
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// run-layer item effect
/// </summary>
public partial struct BuqiRunEffectConfig
{
    public BuqiRunEffectConfig(ByteBuf _buf) 
    {
        Trigger = (BuqiRunTrigger)_buf.ReadInt();
        Effect = (BuqiRunEffect)_buf.ReadInt();
        Amount = _buf.ReadInt();
        Threshold = _buf.ReadInt();
        MaxPerDay = _buf.ReadInt();
        ReasonCode = _buf.ReadString();
        PostInit();
    }

    public static BuqiRunEffectConfig DeserializeBuqiRunEffectConfig(ByteBuf _buf)
    {
        return new BuqiRunEffectConfig(_buf);
    }

    /// <summary>
    /// run trigger
    /// </summary>
    public readonly BuqiRunTrigger Trigger;
    /// <summary>
    /// run effect
    /// </summary>
    public readonly BuqiRunEffect Effect;
    /// <summary>
    /// effect amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// trigger threshold
    /// </summary>
    public readonly int Threshold;
    /// <summary>
    /// daily cap
    /// </summary>
    public readonly int MaxPerDay;
    /// <summary>
    /// stable reason code
    /// </summary>
    public readonly string ReasonCode;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Trigger:" + Trigger + ","
        + "Effect:" + Effect + ","
        + "Amount:" + Amount + ","
        + "Threshold:" + Threshold + ","
        + "MaxPerDay:" + MaxPerDay + ","
        + "ReasonCode:" + ReasonCode + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
