
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// merchant supply specialty
    /// </summary>
    public enum BuqiMerchantSpecialty
    {
        /// <summary>
        /// mixed item pool
        /// </summary>
        General = 0,
        /// <summary>
        /// non-weapon-only pool
        /// </summary>
        NonWeaponOnly = 1,
    }

} 

