
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// event option cost
    /// </summary>
    public enum BuqiEventCostKind
    {
        /// <summary>
        /// no cost
        /// </summary>
        None = 0,
        /// <summary>
        /// coin cost
        /// </summary>
        Coins = 1,
        /// <summary>
        /// life cost
        /// </summary>
        Life = 2,
        /// <summary>
        /// remove item by tag
        /// </summary>
        ItemTag = 3,
        /// <summary>
        /// next battle noise debt
        /// </summary>
        NoiseDebt = 4,
    }

} 

