
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// run-layer effect
    /// </summary>
    public enum BuqiRunEffect
    {
        /// <summary>
        /// gain coin
        /// </summary>
        GainCoin = 0,
        /// <summary>
        /// discount coin
        /// </summary>
        DiscountCoin = 1,
    }

} 

