
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// event option outcome
    /// </summary>
    public enum BuqiEventOutcomeKind
    {
        /// <summary>
        /// gain coins
        /// </summary>
        Coins = 0,
        /// <summary>
        /// gain life
        /// </summary>
        Life = 1,
        /// <summary>
        /// grant item by constrained tag
        /// </summary>
        GrantItemTag = 2,
        /// <summary>
        /// grant refinement
        /// </summary>
        GrantRefinement = 3,
        /// <summary>
        /// upgrade item by tag
        /// </summary>
        UpgradeItemTag = 4,
        /// <summary>
        /// temporary haste
        /// </summary>
        TemporaryHaste = 5,
        /// <summary>
        /// temporary buffer
        /// </summary>
        TemporaryBuffer = 6,
        /// <summary>
        /// temporary healing
        /// </summary>
        TemporaryHealing = 7,
        /// <summary>
        /// next battle noise debt
        /// </summary>
        NoiseDebt = 8,
        /// <summary>
        /// free shop refresh
        /// </summary>
        FreeRefresh = 9,
        /// <summary>
        /// shop discount
        /// </summary>
        ShopDiscount = 10,
        /// <summary>
        /// set run flag
        /// </summary>
        SetFlag = 11,
        /// <summary>
        /// clear run flag
        /// </summary>
        ClearFlag = 12,
        /// <summary>
        /// remove item by tag
        /// </summary>
        RemoveItemTag = 13,
    }

} 

