
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// event option outcome
/// </summary>
public partial struct BuqiEventOutcomeConfig
{
    public BuqiEventOutcomeConfig(ByteBuf _buf) 
    {
        Kind = (BuqiEventOutcomeKind)_buf.ReadInt();
        Amount = _buf.ReadInt();
        Value = _buf.ReadString();
        DurationDays = _buf.ReadInt();
        ReasonCode = _buf.ReadString();
        PostInit();
    }

    public static BuqiEventOutcomeConfig DeserializeBuqiEventOutcomeConfig(ByteBuf _buf)
    {
        return new BuqiEventOutcomeConfig(_buf);
    }

    /// <summary>
    /// outcome kind
    /// </summary>
    public readonly BuqiEventOutcomeKind Kind;
    /// <summary>
    /// outcome amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// outcome qualifier
    /// </summary>
    public readonly string Value;
    /// <summary>
    /// duration in days
    /// </summary>
    public readonly int DurationDays;
    /// <summary>
    /// stable reason code
    /// </summary>
    public readonly string ReasonCode;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Kind:" + Kind + ","
        + "Amount:" + Amount + ","
        + "Value:" + Value + ","
        + "DurationDays:" + DurationDays + ","
        + "ReasonCode:" + ReasonCode + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
