
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// event option condition
    /// </summary>
    public enum BuqiEventConditionKind
    {
        /// <summary>
        /// always visible
        /// </summary>
        None = 0,
        /// <summary>
        /// minimum coins
        /// </summary>
        MinCoins = 1,
        /// <summary>
        /// has item tag
        /// </summary>
        HasItemTag = 2,
        /// <summary>
        /// has build
        /// </summary>
        HasBuild = 3,
        /// <summary>
        /// has quality
        /// </summary>
        HasQuality = 4,
        /// <summary>
        /// has run flag
        /// </summary>
        HasFlag = 5,
        /// <summary>
        /// missing run flag
        /// </summary>
        MissingFlag = 6,
        /// <summary>
        /// maximum lives
        /// </summary>
        MaxLives = 7,
        /// <summary>
        /// exact day
        /// </summary>
        DayEquals = 8,
    }

} 

