
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// normal
    /// </summary>
    public enum BuqiQuality
    {
        /// <summary>
        /// normal
        /// </summary>
        Normal = 1,
        /// <summary>
        /// improved
        /// </summary>
        Improved = 2,
        /// <summary>
        /// fixed
        /// </summary>
        Fixed = 3,
    }

} 

