
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// on use
    /// </summary>
    public enum BuqiTrigger
    {
        /// <summary>
        /// on use
        /// </summary>
        OnUse = 0,
        /// <summary>
        /// battle start
        /// </summary>
        OnBattleStart = 1,
        /// <summary>
        /// adjacent use
        /// </summary>
        OnAdjacentUse = 2,
        /// <summary>
        /// first condition
        /// </summary>
        OnFirstConditionMet = 3,
        /// <summary>
        /// use count
        /// </summary>
        OnUseCountReached = 4,
        /// <summary>
        /// first interfered
        /// </summary>
        OnFirstInterfered = 5,
    }

} 

