
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// run-layer trigger
    /// </summary>
    public enum BuqiRunTrigger
    {
        /// <summary>
        /// no trigger
        /// </summary>
        None = 0,
        /// <summary>
        /// battle-end damage threshold
        /// </summary>
        OnBattleEndDamage = 1,
        /// <summary>
        /// battle-end effective buffer threshold
        /// </summary>
        OnBattleEndBufferAbsorbed = 2,
        /// <summary>
        /// battle-end effective healing threshold
        /// </summary>
        OnBattleEndHealing = 3,
        /// <summary>
        /// first purchase or upgrade per day
        /// </summary>
        OnFirstPurchaseOrUpgrade = 4,
    }

} 

