
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// merchant constrained slot
    /// </summary>
    public enum BuqiMerchantSlotKind
    {
        /// <summary>
        /// build filter
        /// </summary>
        Archetype = 0,
        /// <summary>
        /// size filter
        /// </summary>
        Size = 1,
        /// <summary>
        /// quality filter
        /// </summary>
        Quality = 2,
        /// <summary>
        /// day stage filter
        /// </summary>
        Stage = 3,
        /// <summary>
        /// bridge slot
        /// </summary>
        Bridge = 4,
        /// <summary>
        /// counter slot
        /// </summary>
        Counter = 5,
        /// <summary>
        /// economy slot
        /// </summary>
        Economy = 6,
    }

} 

