
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// single battle effect config
/// </summary>
public partial struct BuqiEffectConfig
{
    public BuqiEffectConfig(ByteBuf _buf) 
    {
        Trigger = (BuqiTrigger)_buf.ReadInt();
        Effect = (BuqiEffect)_buf.ReadInt();
        Target = (BuqiTarget)_buf.ReadInt();
        Amount = _buf.ReadInt();
        DurationTicks = _buf.ReadInt();
        ReasonCode = _buf.ReadString();
        ConditionKind = (BuqiConditionKind)_buf.ReadInt();
        ConditionThreshold = _buf.ReadInt();
        UseCountThreshold = _buf.ReadInt();
        ChargeReadLimit = _buf.ReadInt();
        AmountPerCharge = _buf.ReadInt();
        ChargeConsume = _buf.ReadBool();
        ResetCountOnReached = _buf.ReadBool();
        PostInit();
    }

    public static BuqiEffectConfig DeserializeBuqiEffectConfig(ByteBuf _buf)
    {
        return new BuqiEffectConfig(_buf);
    }

    /// <summary>
    /// trigger
    /// </summary>
    public readonly BuqiTrigger Trigger;
    /// <summary>
    /// effect
    /// </summary>
    public readonly BuqiEffect Effect;
    /// <summary>
    /// target
    /// </summary>
    public readonly BuqiTarget Target;
    /// <summary>
    /// amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// duration ticks
    /// </summary>
    public readonly int DurationTicks;
    /// <summary>
    /// stable reason code
    /// </summary>
    public readonly string ReasonCode;
    /// <summary>
    /// condition kind
    /// </summary>
    public readonly BuqiConditionKind ConditionKind;
    /// <summary>
    /// condition threshold
    /// </summary>
    public readonly int ConditionThreshold;
    /// <summary>
    /// use count threshold
    /// </summary>
    public readonly int UseCountThreshold;
    /// <summary>
    /// charge read limit
    /// </summary>
    public readonly int ChargeReadLimit;
    /// <summary>
    /// amount per charge
    /// </summary>
    public readonly int AmountPerCharge;
    /// <summary>
    /// consume charge
    /// </summary>
    public readonly bool ChargeConsume;
    /// <summary>
    /// reset count
    /// </summary>
    public readonly bool ResetCountOnReached;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Trigger:" + Trigger + ","
        + "Effect:" + Effect + ","
        + "Target:" + Target + ","
        + "Amount:" + Amount + ","
        + "DurationTicks:" + DurationTicks + ","
        + "ReasonCode:" + ReasonCode + ","
        + "ConditionKind:" + ConditionKind + ","
        + "ConditionThreshold:" + ConditionThreshold + ","
        + "UseCountThreshold:" + UseCountThreshold + ","
        + "ChargeReadLimit:" + ChargeReadLimit + ","
        + "AmountPerCharge:" + AmountPerCharge + ","
        + "ChargeConsume:" + ChargeConsume + ","
        + "ResetCountOnReached:" + ResetCountOnReached + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
