
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// event option cost
/// </summary>
public partial struct BuqiEventCostConfig
{
    public BuqiEventCostConfig(ByteBuf _buf) 
    {
        Kind = (BuqiEventCostKind)_buf.ReadInt();
        Amount = _buf.ReadInt();
        Value = _buf.ReadString();
        PostInit();
    }

    public static BuqiEventCostConfig DeserializeBuqiEventCostConfig(ByteBuf _buf)
    {
        return new BuqiEventCostConfig(_buf);
    }

    /// <summary>
    /// cost kind
    /// </summary>
    public readonly BuqiEventCostKind Kind;
    /// <summary>
    /// cost amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// cost qualifier
    /// </summary>
    public readonly string Value;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Kind:" + Kind + ","
        + "Amount:" + Amount + ","
        + "Value:" + Value + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
