
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// training project effect
    /// </summary>
    public enum BuqiTrainingEffectKind
    {
        /// <summary>
        /// cooldown percentage
        /// </summary>
        CooldownPercent = 0,
        /// <summary>
        /// opening haste
        /// </summary>
        OpeningHaste = 1,
        /// <summary>
        /// adjacent haste
        /// </summary>
        AdjacentHaste = 2,
        /// <summary>
        /// opening buffer
        /// </summary>
        OpeningBuffer = 3,
        /// <summary>
        /// buffer gain percentage
        /// </summary>
        BufferGainPercent = 4,
        /// <summary>
        /// first interference ward
        /// </summary>
        FirstInterferenceWard = 5,
        /// <summary>
        /// opening heal
        /// </summary>
        OpeningHeal = 6,
        /// <summary>
        /// healing percentage
        /// </summary>
        HealingPercent = 7,
        /// <summary>
        /// regen duration
        /// </summary>
        RegenDuration = 8,
        /// <summary>
        /// upgrade discount
        /// </summary>
        UpgradeDiscount = 9,
        /// <summary>
        /// refinement discount
        /// </summary>
        RefinementDiscount = 10,
        /// <summary>
        /// free shop reroll
        /// </summary>
        ShopReroll = 11,
    }

} 

