
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// single battle effect config
/// </summary>
public partial struct BuqiEffectConfig
{
    public BuqiEffectConfig(ByteBuf _buf) 
    {
        Trigger = (BuqiTrigger)_buf.ReadInt();
        Effect = (BuqiEffect)_buf.ReadInt();
        Target = (BuqiTarget)_buf.ReadInt();
        Amount = _buf.ReadInt();
        DurationTicks = _buf.ReadInt();
        ReasonCode = _buf.ReadString();
        ConditionKind = (BuqiConditionKind)_buf.ReadInt();
        ConditionThreshold = _buf.ReadInt();
        UseCountThreshold = _buf.ReadInt();
        CriticalChanceBps = _buf.ReadInt();
        RepeatCount = _buf.ReadInt();
        RageThreshold = _buf.ReadInt();
        RageDurationTicks = _buf.ReadInt();
        RageCooldownReductionBps = _buf.ReadInt();
        FlightDamageBonusBps = _buf.ReadInt();
        FlightEndDamage = _buf.ReadInt();
        ResetCountOnReached = _buf.ReadBool();
        PostInit();
    }

    public static BuqiEffectConfig DeserializeBuqiEffectConfig(ByteBuf _buf)
    {
        return new BuqiEffectConfig(_buf);
    }

    /// <summary>
    /// trigger
    /// </summary>
    public readonly BuqiTrigger Trigger;
    /// <summary>
    /// effect
    /// </summary>
    public readonly BuqiEffect Effect;
    /// <summary>
    /// target
    /// </summary>
    public readonly BuqiTarget Target;
    /// <summary>
    /// amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// duration ticks
    /// </summary>
    public readonly int DurationTicks;
    /// <summary>
    /// stable reason code
    /// </summary>
    public readonly string ReasonCode;
    /// <summary>
    /// condition kind
    /// </summary>
    public readonly BuqiConditionKind ConditionKind;
    /// <summary>
    /// condition threshold
    /// </summary>
    public readonly int ConditionThreshold;
    /// <summary>
    /// use count threshold
    /// </summary>
    public readonly int UseCountThreshold;
    /// <summary>
    /// critical chance in basis points
    /// </summary>
    public readonly int CriticalChanceBps;
    /// <summary>
    /// settlement repeat count
    /// </summary>
    public readonly int RepeatCount;
    /// <summary>
    /// rage activation threshold
    /// </summary>
    public readonly int RageThreshold;
    /// <summary>
    /// rage duration ticks
    /// </summary>
    public readonly int RageDurationTicks;
    /// <summary>
    /// rage cooldown reduction in basis points
    /// </summary>
    public readonly int RageCooldownReductionBps;
    /// <summary>
    /// flight damage bonus in basis points
    /// </summary>
    public readonly int FlightDamageBonusBps;
    /// <summary>
    /// damage dealt when leaving flight
    /// </summary>
    public readonly int FlightEndDamage;
    /// <summary>
    /// reset count
    /// </summary>
    public readonly bool ResetCountOnReached;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Trigger:" + Trigger + ","
        + "Effect:" + Effect + ","
        + "Target:" + Target + ","
        + "Amount:" + Amount + ","
        + "DurationTicks:" + DurationTicks + ","
        + "ReasonCode:" + ReasonCode + ","
        + "ConditionKind:" + ConditionKind + ","
        + "ConditionThreshold:" + ConditionThreshold + ","
        + "UseCountThreshold:" + UseCountThreshold + ","
        + "CriticalChanceBps:" + CriticalChanceBps + ","
        + "RepeatCount:" + RepeatCount + ","
        + "RageThreshold:" + RageThreshold + ","
        + "RageDurationTicks:" + RageDurationTicks + ","
        + "RageCooldownReductionBps:" + RageCooldownReductionBps + ","
        + "FlightDamageBonusBps:" + FlightDamageBonusBps + ","
        + "FlightEndDamage:" + FlightEndDamage + ","
        + "ResetCountOnReached:" + ResetCountOnReached + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
