
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// echo build snapshot
/// </summary>
public partial struct BuqiBuildSnapshotConfig
{
    public BuqiBuildSnapshotConfig(ByteBuf _buf) 
    {
        SnapshotId = _buf.ReadString();
        ArchetypeId = (BuqiBuild)_buf.ReadInt();
        InitialExecution = _buf.ReadInt();
        InitialBuffer = _buf.ReadInt();
        InitialNoiseDebt = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Items = new System.Collections.Generic.List<BuqiItemInstanceConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuqiItemInstanceConfig _e0;  _e0 = global::Game.Hot.BuqiItemInstanceConfig.DeserializeBuqiItemInstanceConfig(_buf); Items.Add(_e0);}}
        PostInit();
    }

    public static BuqiBuildSnapshotConfig DeserializeBuqiBuildSnapshotConfig(ByteBuf _buf)
    {
        return new BuqiBuildSnapshotConfig(_buf);
    }

    /// <summary>
    /// snapshot id
    /// </summary>
    public readonly string SnapshotId;
    /// <summary>
    /// build archetype
    /// </summary>
    public readonly BuqiBuild ArchetypeId;
    /// <summary>
    /// initial execution
    /// </summary>
    public readonly int InitialExecution;
    /// <summary>
    /// initial buffer
    /// </summary>
    public readonly int InitialBuffer;
    /// <summary>
    /// initial noise debt
    /// </summary>
    public readonly int InitialNoiseDebt;
    /// <summary>
    /// board item instances
    /// </summary>
    public readonly System.Collections.Generic.List<BuqiItemInstanceConfig> Items;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "SnapshotId:" + SnapshotId + ","
        + "ArchetypeId:" + ArchetypeId + ","
        + "InitialExecution:" + InitialExecution + ","
        + "InitialBuffer:" + InitialBuffer + ","
        + "InitialNoiseDebt:" + InitialNoiseDebt + ","
        + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
