
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// battle build archetype
    /// </summary>
    public enum BuqiBuild
    {
        /// <summary>
        /// attack tempo
        /// </summary>
        fast = 1,
        /// <summary>
        /// shield counter
        /// </summary>
        buffer = 2,
        /// <summary>
        /// charge chain
        /// </summary>
        chain = 3,
        /// <summary>
        /// healing sustain
        /// </summary>
        heal = 4,
        /// <summary>
        /// poison attrition
        /// </summary>
        poison = 5,
        /// <summary>
        /// burn pressure
        /// </summary>
        burn = 6,
        /// <summary>
        /// freeze control
        /// </summary>
        freeze = 7,
        /// <summary>
        /// overload engine
        /// </summary>
        overload = 8,
    }

} 

