
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// echo board item instance
/// </summary>
public partial struct BuqiItemInstanceConfig
{
    public BuqiItemInstanceConfig(ByteBuf _buf) 
    {
        InstanceId = _buf.ReadString();
        DefinitionId = _buf.ReadString();
        DefinitionId_Ref = null;
        Quality = (BuqiQuality)_buf.ReadInt();
        AnchorSlot = _buf.ReadInt();
        RefinementId = _buf.ReadString();
        PostInit();
    }

    public static BuqiItemInstanceConfig DeserializeBuqiItemInstanceConfig(ByteBuf _buf)
    {
        return new BuqiItemInstanceConfig(_buf);
    }

    /// <summary>
    /// instance id
    /// </summary>
    public readonly string InstanceId;
    /// <summary>
    /// item id
    /// </summary>
    public readonly string DefinitionId;
    public DRBuqiItem DefinitionId_Ref { private set; get; }
    /// <summary>
    /// quality
    /// </summary>
    public readonly BuqiQuality Quality;
    /// <summary>
    /// anchor slot
    /// </summary>
    public readonly int AnchorSlot;
    /// <summary>
    /// refinement id
    /// </summary>
    public readonly string RefinementId;

    public  void ResolveRef(TablesComponent tables)
    {
        DefinitionId_Ref = tables.DTBuqiItem.GetOrDefault(DefinitionId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "InstanceId:" + InstanceId + ","
        + "DefinitionId:" + DefinitionId + ","
        + "Quality:" + Quality + ","
        + "AnchorSlot:" + AnchorSlot + ","
        + "RefinementId:" + RefinementId + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
