
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// battle effect
    /// </summary>
    public enum BuqiEffect
    {
        /// <summary>
        /// attack
        /// </summary>
        Damage = 0,
        /// <summary>
        /// shield
        /// </summary>
        Buffer = 1,
        /// <summary>
        /// haste
        /// </summary>
        Haste = 2,
        /// <summary>
        /// slow
        /// </summary>
        Delay = 3,
        /// <summary>
        /// charge
        /// </summary>
        Charge = 4,
        /// <summary>
        /// overload
        /// </summary>
        Noise = 5,
        /// <summary>
        /// heal
        /// </summary>
        Heal = 6,
        /// <summary>
        /// life regen
        /// </summary>
        Regen = 7,
        /// <summary>
        /// poison
        /// </summary>
        Poison = 8,
        /// <summary>
        /// burn
        /// </summary>
        Burn = 9,
        /// <summary>
        /// freeze
        /// </summary>
        Freeze = 10,
        /// <summary>
        /// ammo refill
        /// </summary>
        Ammo = 11,
        /// <summary>
        /// enter or leave flight
        /// </summary>
        Flight = 12,
        /// <summary>
        /// rage accumulation
        /// </summary>
        Rage = 13,
    }

} 

