
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// none
    /// </summary>
    public enum BuqiConditionKind
    {
        /// <summary>
        /// none
        /// </summary>
        None = 0,
        /// <summary>
        /// buffer lost
        /// </summary>
        BufferLost = 1,
        /// <summary>
        /// charge at least
        /// </summary>
        ChargeAtLeast = 2,
    }

} 

