
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// fast execution
    /// </summary>
    public enum BuqiBuild
    {
        /// <summary>
        /// fast execution
        /// </summary>
        fast = 1,
        /// <summary>
        /// buffer counter
        /// </summary>
        buffer = 2,
        /// <summary>
        /// chain engine
        /// </summary>
        chain = 3,
    }

} 

