
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// damage
    /// </summary>
    public enum BuqiEffect
    {
        /// <summary>
        /// damage
        /// </summary>
        Damage = 0,
        /// <summary>
        /// buffer
        /// </summary>
        Buffer = 1,
        /// <summary>
        /// haste
        /// </summary>
        Haste = 2,
        /// <summary>
        /// delay
        /// </summary>
        Delay = 3,
        /// <summary>
        /// charge
        /// </summary>
        Charge = 4,
        /// <summary>
        /// noise
        /// </summary>
        Noise = 5,
    }

} 

