
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// 1 slot
    /// </summary>
    public enum BuqiSize
    {
        /// <summary>
        /// 1 slot
        /// </summary>
        S = 1,
        /// <summary>
        /// 2 slots
        /// </summary>
        M = 2,
        /// <summary>
        /// 3 slots
        /// </summary>
        L = 3,
    }

} 

