
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// formal supply category
    /// </summary>
    public enum BuqiItemCategory
    {
        /// <summary>
        /// invalid / missing classification
        /// </summary>
        Unknown = 0,
        /// <summary>
        /// non-weapon item
        /// </summary>
        NonWeapon = 1,
        /// <summary>
        /// formal weapon item
        /// </summary>
        Weapon = 2,
    }

} 

