
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Hot
{ 
    /// <summary>
    /// enemy execution
    /// </summary>
    public enum BuqiTarget
    {
        /// <summary>
        /// enemy execution
        /// </summary>
        EnemyExecution = 0,
        /// <summary>
        /// self
        /// </summary>
        Self = 1,
        /// <summary>
        /// left adjacent
        /// </summary>
        LeftAdjacentItem = 2,
        /// <summary>
        /// right adjacent
        /// </summary>
        RightAdjacentItem = 3,
        /// <summary>
        /// all adjacent
        /// </summary>
        AllAdjacentItems = 4,
        /// <summary>
        /// enemy shortest cooldown
        /// </summary>
        ShortestCooldownEnemyItem = 5,
        /// <summary>
        /// enemy longest cooldown
        /// </summary>
        LongestCooldownEnemyItem = 6,
        /// <summary>
        /// enemy leftmost
        /// </summary>
        LeftmostEnemyItem = 7,
        /// <summary>
        /// enemy rightmost
        /// </summary>
        RightmostEnemyItem = 8,
    }

} 

