
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiRefinement : Luban.BeanBase
{
    public DRBuqiRefinement(ByteBuf _buf) 
    {
        RefinementId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        Summary = _buf.ReadString();
        PostInit();
    }

    public static DRBuqiRefinement DeserializeDRBuqiRefinement(ByteBuf _buf)
    {
        return new DRBuqiRefinement(_buf);
    }

    /// <summary>
    /// refinement id
    /// </summary>
    public readonly string RefinementId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// summary
    /// </summary>
    public readonly string Summary;
    public const int __ID__ = -42868348;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "RefinementId:" + RefinementId + ","
        + "DisplayName:" + DisplayName + ","
        + "Summary:" + Summary + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
