
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiEcho : Luban.BeanBase
{
    public DRBuqiEcho(ByteBuf _buf) 
    {
        EchoId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        Tier = _buf.ReadString();
        Build = (BuqiBuild)_buf.ReadInt();
        Snapshot = global::Game.Hot.BuqiBuildSnapshotConfig.DeserializeBuqiBuildSnapshotConfig(_buf);
        PostInit();
    }

    public static DRBuqiEcho DeserializeDRBuqiEcho(ByteBuf _buf)
    {
        return new DRBuqiEcho(_buf);
    }

    /// <summary>
    /// echo id
    /// </summary>
    public readonly string EchoId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// tier
    /// </summary>
    public readonly string Tier;
    /// <summary>
    /// build
    /// </summary>
    public readonly BuqiBuild Build;
    /// <summary>
    /// build snapshot
    /// </summary>
    public readonly BuqiBuildSnapshotConfig Snapshot;
    public const int __ID__ = 493904158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "EchoId:" + EchoId + ","
        + "DisplayName:" + DisplayName + ","
        + "Tier:" + Tier + ","
        + "Build:" + Build + ","
        + "Snapshot:" + Snapshot + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
