
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuff : Luban.BeanBase
{
    public DRBuff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        BuffType = (BulletBuffType)_buf.ReadInt();
        PostInit();
    }

    public static DRBuff DeserializeDRBuff(ByteBuf _buf)
    {
        return new DRBuff(_buf);
    }

    /// <summary>
    /// Buff编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly BulletBuffType BuffType;
    public const int __ID__ = 2024592897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Duration:" + Duration + ","
        + "BuffType:" + BuffType + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
