
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiEvent : Luban.BeanBase
{
    public DRBuqiEvent(ByteBuf _buf) 
    {
        EventId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        LocalizationKey = _buf.ReadString();
        MinDay = _buf.ReadInt();
        MaxDay = _buf.ReadInt();
        Weight = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); RequiredFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); RequiredFlags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ForbiddenFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ForbiddenFlags.Add(_e0);}}
        RevisitEventId = _buf.ReadString();
        RevisitDelayDays = _buf.ReadInt();
        DayNineResolution = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); OptionIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); OptionIds.Add(_e0);}}
        PostInit();
    }

    public static DRBuqiEvent DeserializeDRBuqiEvent(ByteBuf _buf)
    {
        return new DRBuqiEvent(_buf);
    }

    /// <summary>
    /// event id
    /// </summary>
    public readonly string EventId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// localization key
    /// </summary>
    public readonly string LocalizationKey;
    /// <summary>
    /// minimum day
    /// </summary>
    public readonly int MinDay;
    /// <summary>
    /// maximum day
    /// </summary>
    public readonly int MaxDay;
    /// <summary>
    /// selection weight
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// required run flags
    /// </summary>
    public readonly System.Collections.Generic.List<string> RequiredFlags;
    /// <summary>
    /// forbidden run flags
    /// </summary>
    public readonly System.Collections.Generic.List<string> ForbiddenFlags;
    /// <summary>
    /// cross-day revisit event
    /// </summary>
    public readonly string RevisitEventId;
    /// <summary>
    /// revisit delay
    /// </summary>
    public readonly int RevisitDelayDays;
    /// <summary>
    /// day nine resolution
    /// </summary>
    public readonly bool DayNineResolution;
    /// <summary>
    /// exactly three option ids
    /// </summary>
    public readonly System.Collections.Generic.List<string> OptionIds;
    public System.Collections.Generic.List<DRBuqiEventOption> OptionIds_Ref { private set; get; }
    public const int __ID__ = -1868277055;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        OptionIds_Ref = new System.Collections.Generic.List<DRBuqiEventOption>();
        foreach (var _v in OptionIds) { OptionIds_Ref.Add(tables.DTBuqiEventOption.GetOrDefault(_v)); }

        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "EventId:" + EventId + ","
        + "DisplayName:" + DisplayName + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "MinDay:" + MinDay + ","
        + "MaxDay:" + MaxDay + ","
        + "Weight:" + Weight + ","
        + "RequiredFlags:" + Luban.StringUtil.CollectionToString(RequiredFlags) + ","
        + "ForbiddenFlags:" + Luban.StringUtil.CollectionToString(ForbiddenFlags) + ","
        + "RevisitEventId:" + RevisitEventId + ","
        + "RevisitDelayDays:" + RevisitDelayDays + ","
        + "DayNineResolution:" + DayNineResolution + ","
        + "OptionIds:" + Luban.StringUtil.CollectionToString(OptionIds) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
