
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiTrainer : Luban.BeanBase
{
    public DRBuqiTrainer(ByteBuf _buf) 
    {
        TrainerId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        LocalizationKey = _buf.ReadString();
        MinDay = _buf.ReadInt();
        MaxDay = _buf.ReadInt();
        Weight = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ProjectIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ProjectIds.Add(_e0);}}
        PostInit();
    }

    public static DRBuqiTrainer DeserializeDRBuqiTrainer(ByteBuf _buf)
    {
        return new DRBuqiTrainer(_buf);
    }

    /// <summary>
    /// trainer id
    /// </summary>
    public readonly string TrainerId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// localization key
    /// </summary>
    public readonly string LocalizationKey;
    /// <summary>
    /// minimum day
    /// </summary>
    public readonly int MinDay;
    /// <summary>
    /// maximum day
    /// </summary>
    public readonly int MaxDay;
    /// <summary>
    /// selection weight
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// training projects
    /// </summary>
    public readonly System.Collections.Generic.List<string> ProjectIds;
    public System.Collections.Generic.List<DRBuqiTrainingProject> ProjectIds_Ref { private set; get; }
    public const int __ID__ = 191371036;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        ProjectIds_Ref = new System.Collections.Generic.List<DRBuqiTrainingProject>();
        foreach (var _v in ProjectIds) { ProjectIds_Ref.Add(tables.DTBuqiTrainingProject.GetOrDefault(_v)); }

        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "TrainerId:" + TrainerId + ","
        + "DisplayName:" + DisplayName + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "MinDay:" + MinDay + ","
        + "MaxDay:" + MaxDay + ","
        + "Weight:" + Weight + ","
        + "ProjectIds:" + Luban.StringUtil.CollectionToString(ProjectIds) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
