
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiItem : Luban.BeanBase
{
    public DRBuqiItem(ByteBuf _buf) 
    {
        DefinitionId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        Size = (BuqiSize)_buf.ReadInt();
        BasePrice = _buf.ReadInt();
        BaseCooldownTicks = _buf.ReadInt();
        ArchetypeId = (BuqiBuild)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Tags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Effects = new System.Collections.Generic.List<BuqiEffectConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuqiEffectConfig _e0;  _e0 = global::Game.Hot.BuqiEffectConfig.DeserializeBuqiEffectConfig(_buf); Effects.Add(_e0);}}
        PostInit();
    }

    public static DRBuqiItem DeserializeDRBuqiItem(ByteBuf _buf)
    {
        return new DRBuqiItem(_buf);
    }

    /// <summary>
    /// item id
    /// </summary>
    public readonly string DefinitionId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// size
    /// </summary>
    public readonly BuqiSize Size;
    /// <summary>
    /// price
    /// </summary>
    public readonly int BasePrice;
    /// <summary>
    /// cooldown ticks
    /// </summary>
    public readonly int BaseCooldownTicks;
    /// <summary>
    /// build
    /// </summary>
    public readonly BuqiBuild ArchetypeId;
    /// <summary>
    /// tags
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// effect list
    /// </summary>
    public readonly System.Collections.Generic.List<BuqiEffectConfig> Effects;
    public const int __ID__ = 494039564;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "DefinitionId:" + DefinitionId + ","
        + "DisplayName:" + DisplayName + ","
        + "Size:" + Size + ","
        + "BasePrice:" + BasePrice + ","
        + "BaseCooldownTicks:" + BaseCooldownTicks + ","
        + "ArchetypeId:" + ArchetypeId + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "Effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
