
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiMerchant : Luban.BeanBase
{
    public DRBuqiMerchant(ByteBuf _buf) 
    {
        MerchantId = _buf.ReadString();
        DisplayName = _buf.ReadString();
        LocalizationKey = _buf.ReadString();
        MinDay = _buf.ReadInt();
        MaxDay = _buf.ReadInt();
        Weight = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PoolItemIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PoolItemIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Slots = new System.Collections.Generic.List<BuqiMerchantSlotConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuqiMerchantSlotConfig _e0;  _e0 = global::Game.Hot.BuqiMerchantSlotConfig.DeserializeBuqiMerchantSlotConfig(_buf); Slots.Add(_e0);}}
        PostInit();
    }

    public static DRBuqiMerchant DeserializeDRBuqiMerchant(ByteBuf _buf)
    {
        return new DRBuqiMerchant(_buf);
    }

    /// <summary>
    /// merchant id
    /// </summary>
    public readonly string MerchantId;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// localization key
    /// </summary>
    public readonly string LocalizationKey;
    /// <summary>
    /// minimum day
    /// </summary>
    public readonly int MinDay;
    /// <summary>
    /// maximum day
    /// </summary>
    public readonly int MaxDay;
    /// <summary>
    /// selection weight
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// constrained item pool
    /// </summary>
    public readonly System.Collections.Generic.List<string> PoolItemIds;
    public System.Collections.Generic.List<DRBuqiItem> PoolItemIds_Ref { private set; get; }
    /// <summary>
    /// offer slot constraints
    /// </summary>
    public readonly System.Collections.Generic.List<BuqiMerchantSlotConfig> Slots;
    public const int __ID__ = -143877055;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PoolItemIds_Ref = new System.Collections.Generic.List<DRBuqiItem>();
        foreach (var _v in PoolItemIds) { PoolItemIds_Ref.Add(tables.DTBuqiItem.GetOrDefault(_v)); }

        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "MerchantId:" + MerchantId + ","
        + "DisplayName:" + DisplayName + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "MinDay:" + MinDay + ","
        + "MaxDay:" + MaxDay + ","
        + "Weight:" + Weight + ","
        + "PoolItemIds:" + Luban.StringUtil.CollectionToString(PoolItemIds) + ","
        + "Slots:" + Luban.StringUtil.CollectionToString(Slots) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
