
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiEventOption : Luban.BeanBase
{
    public DRBuqiEventOption(ByteBuf _buf) 
    {
        OptionId = _buf.ReadString();
        EventId = _buf.ReadString();
        EventId_Ref = null;
        Order = _buf.ReadInt();
        DisplayName = _buf.ReadString();
        LocalizationKey = _buf.ReadString();
        ConditionKind = (BuqiEventConditionKind)_buf.ReadInt();
        ConditionValue = _buf.ReadString();
        {int n0 = _buf.ReadSize(); RequiredFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); RequiredFlags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ForbiddenFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ForbiddenFlags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Costs = new System.Collections.Generic.List<BuqiEventCostConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuqiEventCostConfig _e0;  _e0 = global::Game.Hot.BuqiEventCostConfig.DeserializeBuqiEventCostConfig(_buf); Costs.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Outcomes = new System.Collections.Generic.List<BuqiEventOutcomeConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuqiEventOutcomeConfig _e0;  _e0 = global::Game.Hot.BuqiEventOutcomeConfig.DeserializeBuqiEventOutcomeConfig(_buf); Outcomes.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SetFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SetFlags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ClearFlags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ClearFlags.Add(_e0);}}
        FollowUpEventId = _buf.ReadString();
        FollowUpDelayDays = _buf.ReadInt();
        Summary = _buf.ReadString();
        SummaryLocalizationKey = _buf.ReadString();
        PostInit();
    }

    public static DRBuqiEventOption DeserializeDRBuqiEventOption(ByteBuf _buf)
    {
        return new DRBuqiEventOption(_buf);
    }

    /// <summary>
    /// option id
    /// </summary>
    public readonly string OptionId;
    /// <summary>
    /// event id
    /// </summary>
    public readonly string EventId;
    public DRBuqiEvent EventId_Ref { private set; get; }
    /// <summary>
    /// display order
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// localization key
    /// </summary>
    public readonly string LocalizationKey;
    /// <summary>
    /// condition kind
    /// </summary>
    public readonly BuqiEventConditionKind ConditionKind;
    /// <summary>
    /// condition value
    /// </summary>
    public readonly string ConditionValue;
    /// <summary>
    /// required flags
    /// </summary>
    public readonly System.Collections.Generic.List<string> RequiredFlags;
    /// <summary>
    /// forbidden flags
    /// </summary>
    public readonly System.Collections.Generic.List<string> ForbiddenFlags;
    /// <summary>
    /// cost list
    /// </summary>
    public readonly System.Collections.Generic.List<BuqiEventCostConfig> Costs;
    /// <summary>
    /// outcome list
    /// </summary>
    public readonly System.Collections.Generic.List<BuqiEventOutcomeConfig> Outcomes;
    /// <summary>
    /// flags set
    /// </summary>
    public readonly System.Collections.Generic.List<string> SetFlags;
    /// <summary>
    /// flags cleared
    /// </summary>
    public readonly System.Collections.Generic.List<string> ClearFlags;
    /// <summary>
    /// follow-up event
    /// </summary>
    public readonly string FollowUpEventId;
    /// <summary>
    /// follow-up delay
    /// </summary>
    public readonly int FollowUpDelayDays;
    /// <summary>
    /// visible summary
    /// </summary>
    public readonly string Summary;
    /// <summary>
    /// summary localization key
    /// </summary>
    public readonly string SummaryLocalizationKey;
    public const int __ID__ = -449119594;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        EventId_Ref = tables.DTBuqiEvent.GetOrDefault(EventId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "OptionId:" + OptionId + ","
        + "EventId:" + EventId + ","
        + "Order:" + Order + ","
        + "DisplayName:" + DisplayName + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "ConditionKind:" + ConditionKind + ","
        + "ConditionValue:" + ConditionValue + ","
        + "RequiredFlags:" + Luban.StringUtil.CollectionToString(RequiredFlags) + ","
        + "ForbiddenFlags:" + Luban.StringUtil.CollectionToString(ForbiddenFlags) + ","
        + "Costs:" + Luban.StringUtil.CollectionToString(Costs) + ","
        + "Outcomes:" + Luban.StringUtil.CollectionToString(Outcomes) + ","
        + "SetFlags:" + Luban.StringUtil.CollectionToString(SetFlags) + ","
        + "ClearFlags:" + Luban.StringUtil.CollectionToString(ClearFlags) + ","
        + "FollowUpEventId:" + FollowUpEventId + ","
        + "FollowUpDelayDays:" + FollowUpDelayDays + ","
        + "Summary:" + Summary + ","
        + "SummaryLocalizationKey:" + SummaryLocalizationKey + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
