
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiGlobal : Luban.BeanBase
{
    public DRBuqiGlobal(ByteBuf _buf) 
    {
        ContentVersion = _buf.ReadString();
        InitialExecution = _buf.ReadInt();
        BufferCap = _buf.ReadInt();
        NoiseThreshold = _buf.ReadInt();
        NoiseIncidentDamage = _buf.ReadInt();
        BoardSlotCount = _buf.ReadInt();
        StormStartTicks = _buf.ReadInt();
        StormBaseDamage = _buf.ReadInt();
        StormRampDamage = _buf.ReadInt();
        MaxTickEvents = _buf.ReadInt();
        MaxItemEventsPerTick = _buf.ReadInt();
        MaxChainDepth = _buf.ReadInt();
        MaxRepeatedReasonPerTick = _buf.ReadInt();
        DailyEconomyProcCap = _buf.ReadInt();
        PostInit();
    }

    public static DRBuqiGlobal DeserializeDRBuqiGlobal(ByteBuf _buf)
    {
        return new DRBuqiGlobal(_buf);
    }

    /// <summary>
    /// content version
    /// </summary>
    public readonly string ContentVersion;
    /// <summary>
    /// initial execution
    /// </summary>
    public readonly int InitialExecution;
    /// <summary>
    /// buffer cap
    /// </summary>
    public readonly int BufferCap;
    /// <summary>
    /// noise threshold
    /// </summary>
    public readonly int NoiseThreshold;
    /// <summary>
    /// noise incident damage
    /// </summary>
    public readonly int NoiseIncidentDamage;
    /// <summary>
    /// board slots
    /// </summary>
    public readonly int BoardSlotCount;
    /// <summary>
    /// storm start ticks
    /// </summary>
    public readonly int StormStartTicks;
    /// <summary>
    /// storm base true damage
    /// </summary>
    public readonly int StormBaseDamage;
    /// <summary>
    /// storm true damage gained per tick
    /// </summary>
    public readonly int StormRampDamage;
    /// <summary>
    /// max tick events
    /// </summary>
    public readonly int MaxTickEvents;
    /// <summary>
    /// max item events per tick
    /// </summary>
    public readonly int MaxItemEventsPerTick;
    /// <summary>
    /// maximum trigger chain depth
    /// </summary>
    public readonly int MaxChainDepth;
    /// <summary>
    /// maximum repeated reason code per tick
    /// </summary>
    public readonly int MaxRepeatedReasonPerTick;
    /// <summary>
    /// maximum economy item proc per day
    /// </summary>
    public readonly int DailyEconomyProcCap;
    public const int __ID__ = -2033704868;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "ContentVersion:" + ContentVersion + ","
        + "InitialExecution:" + InitialExecution + ","
        + "BufferCap:" + BufferCap + ","
        + "NoiseThreshold:" + NoiseThreshold + ","
        + "NoiseIncidentDamage:" + NoiseIncidentDamage + ","
        + "BoardSlotCount:" + BoardSlotCount + ","
        + "StormStartTicks:" + StormStartTicks + ","
        + "StormBaseDamage:" + StormBaseDamage + ","
        + "StormRampDamage:" + StormRampDamage + ","
        + "MaxTickEvents:" + MaxTickEvents + ","
        + "MaxItemEventsPerTick:" + MaxItemEventsPerTick + ","
        + "MaxChainDepth:" + MaxChainDepth + ","
        + "MaxRepeatedReasonPerTick:" + MaxRepeatedReasonPerTick + ","
        + "DailyEconomyProcCap:" + DailyEconomyProcCap + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
