
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public sealed partial class DRBuqiTrainingProject : Luban.BeanBase
{
    public DRBuqiTrainingProject(ByteBuf _buf) 
    {
        ProjectId = _buf.ReadString();
        TrainerId = _buf.ReadString();
        TrainerId_Ref = null;
        DisplayName = _buf.ReadString();
        LocalizationKey = _buf.ReadString();
        MinDay = _buf.ReadInt();
        MaxDay = _buf.ReadInt();
        Cost = _buf.ReadInt();
        RequiredTag = _buf.ReadString();
        ExcludedTag = _buf.ReadString();
        EffectKind = (BuqiTrainingEffectKind)_buf.ReadInt();
        Amount = _buf.ReadInt();
        Duration = _buf.ReadInt();
        MaxPerRun = _buf.ReadInt();
        Summary = _buf.ReadString();
        SummaryLocalizationKey = _buf.ReadString();
        PostInit();
    }

    public static DRBuqiTrainingProject DeserializeDRBuqiTrainingProject(ByteBuf _buf)
    {
        return new DRBuqiTrainingProject(_buf);
    }

    /// <summary>
    /// project id
    /// </summary>
    public readonly string ProjectId;
    /// <summary>
    /// trainer id
    /// </summary>
    public readonly string TrainerId;
    public DRBuqiTrainer TrainerId_Ref { private set; get; }
    /// <summary>
    /// display name
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// localization key
    /// </summary>
    public readonly string LocalizationKey;
    /// <summary>
    /// minimum day
    /// </summary>
    public readonly int MinDay;
    /// <summary>
    /// maximum day
    /// </summary>
    public readonly int MaxDay;
    /// <summary>
    /// coin cost
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// required item tag
    /// </summary>
    public readonly string RequiredTag;
    /// <summary>
    /// excluded item tag
    /// </summary>
    public readonly string ExcludedTag;
    /// <summary>
    /// effect kind
    /// </summary>
    public readonly BuqiTrainingEffectKind EffectKind;
    /// <summary>
    /// amount
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// duration
    /// </summary>
    public readonly int Duration;
    /// <summary>
    /// run cap
    /// </summary>
    public readonly int MaxPerRun;
    /// <summary>
    /// summary
    /// </summary>
    public readonly string Summary;
    /// <summary>
    /// summary localization key
    /// </summary>
    public readonly string SummaryLocalizationKey;
    public const int __ID__ = 491992134;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TablesComponent tables)
    {
        TrainerId_Ref = tables.DTBuqiTrainer.GetOrDefault(TrainerId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "ProjectId:" + ProjectId + ","
        + "TrainerId:" + TrainerId + ","
        + "DisplayName:" + DisplayName + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "MinDay:" + MinDay + ","
        + "MaxDay:" + MaxDay + ","
        + "Cost:" + Cost + ","
        + "RequiredTag:" + RequiredTag + ","
        + "ExcludedTag:" + ExcludedTag + ","
        + "EffectKind:" + EffectKind + ","
        + "Amount:" + Amount + ","
        + "Duration:" + Duration + ","
        + "MaxPerRun:" + MaxPerRun + ","
        + "Summary:" + Summary + ","
        + "SummaryLocalizationKey:" + SummaryLocalizationKey + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
