
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// Buqi trainers
/// </summary>
public partial class DTBuqiTrainer : IDataTable
{
    private System.Collections.Generic.Dictionary<string, DRBuqiTrainer> _dataMap;
    private System.Collections.Generic.List<DRBuqiTrainer> _dataList;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTBuqiTrainer(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if(_dataMap == null)
        {
            _dataMap = new System.Collections.Generic.Dictionary<string, DRBuqiTrainer>(n);
            _dataList = new System.Collections.Generic.List<DRBuqiTrainer>(n);
        }
        else
        {
            _dataMap.Clear();
            _dataList.Clear();
        }
        for(int i = n ; i > 0 ; --i)
        {
            DRBuqiTrainer _v;
            _v = global::Game.Hot.DRBuqiTrainer.DeserializeDRBuqiTrainer(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TrainerId, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, DRBuqiTrainer> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DRBuqiTrainer> DataList => _dataList;
    public DRBuqiTrainer GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRBuqiTrainer Get(string key) => _dataMap[key];
    public DRBuqiTrainer this[string key] => _dataMap[key];

    public void ResolveRef(TablesComponent tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }


    partial void PostInit();
    partial void PostResolveRef();
}
}
