
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// Buff表
/// </summary>
public partial class DTBuff : IDataTable
{
    private readonly System.Collections.Generic.Dictionary<int, DRBuff> _dataMap;
    private readonly System.Collections.Generic.List<DRBuff> _dataList;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTBuff(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
        _dataMap = new System.Collections.Generic.Dictionary<int, DRBuff>();
        _dataList = new System.Collections.Generic.List<DRBuff>();
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        _dataMap.Clear();
        _dataList.Clear();
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DRBuff _v;
            _v = global::Game.Hot.DRBuff.DeserializeDRBuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, DRBuff> DataMap => _dataMap;
    public System.Collections.Generic.List<DRBuff> DataList => _dataList;
    public DRBuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DRBuff Get(int key) => _dataMap[key];
    public DRBuff this[int key] => _dataMap[key];

    public void ResolveRef(TablesComponent tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }


    partial void PostInit();
    partial void PostResolveRef();
}
}
