
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
/// <summary>
/// Buqi global battle rules
/// </summary>
public partial class DTBuqiGlobal : IDataTable
{

    private DRBuqiGlobal _data;
    public DRBuqiGlobal Data => _data;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTBuqiGlobal(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::Game.Hot.DRBuqiGlobal.DeserializeDRBuqiGlobal(_buf);
        PostInit();
    }

    /// <summary>
    /// content version
    /// </summary>
    public string ContentVersion => _data.ContentVersion;
    /// <summary>
    /// initial execution
    /// </summary>
    public int InitialExecution => _data.InitialExecution;
    /// <summary>
    /// buffer cap
    /// </summary>
    public int BufferCap => _data.BufferCap;
    /// <summary>
    /// noise threshold
    /// </summary>
    public int NoiseThreshold => _data.NoiseThreshold;
    /// <summary>
    /// noise incident damage
    /// </summary>
    public int NoiseIncidentDamage => _data.NoiseIncidentDamage;
    /// <summary>
    /// board slots
    /// </summary>
    public int BoardSlotCount => _data.BoardSlotCount;
    /// <summary>
    /// normal duration ticks
    /// </summary>
    public int NormalDurationTicks => _data.NormalDurationTicks;
    /// <summary>
    /// hard cap ticks
    /// </summary>
    public int HardCapTicks => _data.HardCapTicks;
    /// <summary>
    /// overtime start ticks
    /// </summary>
    public int OvertimeStartTicks => _data.OvertimeStartTicks;
    /// <summary>
    /// max tick events
    /// </summary>
    public int MaxTickEvents => _data.MaxTickEvents;
    /// <summary>
    /// max item events per tick
    /// </summary>
    public int MaxItemEventsPerTick => _data.MaxItemEventsPerTick;
    /// <summary>
    /// maximum trigger chain depth
    /// </summary>
    public int MaxChainDepth => _data.MaxChainDepth;
    /// <summary>
    /// maximum repeated reason code per tick
    /// </summary>
    public int MaxRepeatedReasonPerTick => _data.MaxRepeatedReasonPerTick;
    /// <summary>
    /// maximum economy item proc per day
    /// </summary>
    public int DailyEconomyProcCap => _data.DailyEconomyProcCap;

    public void ResolveRef(TablesComponent tables)
    {
        _data.ResolveRef(tables);
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
