
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Hot
{
public partial class TablesComponent
{
    public DTOneConfig DTOneConfig { private set; get; }
    public DTAircraft DTAircraft { private set; get; }
    public DTArmor DTArmor { private set; get; }
    public DTAsteroid DTAsteroid { private set; get; }
    public DTThruster DTThruster { private set; get; }
    public DTWeapon DTWeapon { private set; get; }
    /// <summary>
    /// Buqi global battle rules
    /// </summary>
    public DTBuqiGlobal DTBuqiGlobal { private set; get; }
    /// <summary>
    /// Buqi Step 3 nine items
    /// </summary>
    public DTBuqiItem DTBuqiItem { private set; get; }
    /// <summary>
    /// Buqi Step 3 three refinements
    /// </summary>
    public DTBuqiRefinement DTBuqiRefinement { private set; get; }
    /// <summary>
    /// Buqi Step 3 six echoes
    /// </summary>
    public DTBuqiEcho DTBuqiEcho { private set; get; }
    private System.Collections.Generic.Dictionary<string, IDataTable> _tables;
    public System.Collections.Generic.IEnumerable<IDataTable> DataTables => _tables.Values;
    public IDataTable GetDataTable(string tableName) => _tables.TryGetValue(tableName, out var v) ? v : null;

    public async Cysharp.Threading.Tasks.UniTask LoadAsync(System.Func<string, Cysharp.Threading.Tasks.UniTask<ByteBuf>> loader)
    {
        TablesMemory.BeginRecord();

        _tables = new System.Collections.Generic.Dictionary<string, IDataTable>();
        var loadTasks = new System.Collections.Generic.List<Cysharp.Threading.Tasks.UniTask>();

        DTOneConfig = new DTOneConfig(() => loader("dtoneconfig"));
        loadTasks.Add(DTOneConfig.LoadAsync());
        _tables.Add("DTOneConfig", DTOneConfig);
        DTAircraft = new DTAircraft(() => loader("dtaircraft"));
        loadTasks.Add(DTAircraft.LoadAsync());
        _tables.Add("DTAircraft", DTAircraft);
        DTArmor = new DTArmor(() => loader("dtarmor"));
        loadTasks.Add(DTArmor.LoadAsync());
        _tables.Add("DTArmor", DTArmor);
        DTAsteroid = new DTAsteroid(() => loader("dtasteroid"));
        loadTasks.Add(DTAsteroid.LoadAsync());
        _tables.Add("DTAsteroid", DTAsteroid);
        DTThruster = new DTThruster(() => loader("dtthruster"));
        loadTasks.Add(DTThruster.LoadAsync());
        _tables.Add("DTThruster", DTThruster);
        DTWeapon = new DTWeapon(() => loader("dtweapon"));
        loadTasks.Add(DTWeapon.LoadAsync());
        _tables.Add("DTWeapon", DTWeapon);
        DTBuqiGlobal = new DTBuqiGlobal(() => loader("dtbuqiglobal"));
        loadTasks.Add(DTBuqiGlobal.LoadAsync());
        _tables.Add("DTBuqiGlobal", DTBuqiGlobal);
        DTBuqiItem = new DTBuqiItem(() => loader("dtbuqiitem"));
        loadTasks.Add(DTBuqiItem.LoadAsync());
        _tables.Add("DTBuqiItem", DTBuqiItem);
        DTBuqiRefinement = new DTBuqiRefinement(() => loader("dtbuqirefinement"));
        loadTasks.Add(DTBuqiRefinement.LoadAsync());
        _tables.Add("DTBuqiRefinement", DTBuqiRefinement);
        DTBuqiEcho = new DTBuqiEcho(() => loader("dtbuqiecho"));
        loadTasks.Add(DTBuqiEcho.LoadAsync());
        _tables.Add("DTBuqiEcho", DTBuqiEcho);

        await Cysharp.Threading.Tasks.UniTask.WhenAll(loadTasks);

        Refresh();

        TablesMemory.EndRecord();
    }

    private void ResolveRef()
    {
        DTOneConfig.ResolveRef(this);
        DTAircraft.ResolveRef(this);
        DTArmor.ResolveRef(this);
        DTAsteroid.ResolveRef(this);
        DTThruster.ResolveRef(this);
        DTWeapon.ResolveRef(this);
        DTBuqiGlobal.ResolveRef(this);
        DTBuqiItem.ResolveRef(this);
        DTBuqiRefinement.ResolveRef(this);
        DTBuqiEcho.ResolveRef(this);
        PostResolveRef();
    }

    public void Refresh()
    {
        PostInit();
        ResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
