
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    public enum BulletType
    {
        /// <summary>
        /// Linear movement
        /// </summary>
        Linear = 0,
        /// <summary>
        /// Curve movement
        /// </summary>
        Curve = 1,
        /// <summary>
        /// Seeking movement
        /// </summary>
        Seeking = 2,
    }

    public static class BulletType_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Linear = new Luban.EditorEnumItemInfo("Linear", "线性", 0, "Linear movement");
        public static readonly Luban.EditorEnumItemInfo Curve = new Luban.EditorEnumItemInfo("Curve", "曲线", 1, "Curve movement");
        public static readonly Luban.EditorEnumItemInfo Seeking = new Luban.EditorEnumItemInfo("Seeking", "追踪", 2, "Seeking movement");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Linear,
            Curve,
            Seeking,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

