
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// normal
    /// </summary>
    public enum BuqiQuality
    {
        /// <summary>
        /// normal
        /// </summary>
        Normal = 1,
        /// <summary>
        /// improved
        /// </summary>
        Improved = 2,
        /// <summary>
        /// fixed
        /// </summary>
        Fixed = 3,
    }

    public static class BuqiQuality_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Normal = new Luban.EditorEnumItemInfo("Normal", "", 1, "normal");
        public static readonly Luban.EditorEnumItemInfo Improved = new Luban.EditorEnumItemInfo("Improved", "", 2, "improved");
        public static readonly Luban.EditorEnumItemInfo Fixed = new Luban.EditorEnumItemInfo("Fixed", "", 3, "fixed");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Normal,
            Improved,
            Fixed,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

