
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// event option condition
    /// </summary>
    public enum BuqiEventConditionKind
    {
        /// <summary>
        /// always visible
        /// </summary>
        None = 0,
        /// <summary>
        /// minimum coins
        /// </summary>
        MinCoins = 1,
        /// <summary>
        /// has item tag
        /// </summary>
        HasItemTag = 2,
        /// <summary>
        /// has build
        /// </summary>
        HasBuild = 3,
        /// <summary>
        /// has quality
        /// </summary>
        HasQuality = 4,
        /// <summary>
        /// has run flag
        /// </summary>
        HasFlag = 5,
        /// <summary>
        /// missing run flag
        /// </summary>
        MissingFlag = 6,
        /// <summary>
        /// maximum lives
        /// </summary>
        MaxLives = 7,
        /// <summary>
        /// exact day
        /// </summary>
        DayEquals = 8,
    }

    public static class BuqiEventConditionKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "", 0, "always visible");
        public static readonly Luban.EditorEnumItemInfo MinCoins = new Luban.EditorEnumItemInfo("MinCoins", "", 1, "minimum coins");
        public static readonly Luban.EditorEnumItemInfo HasItemTag = new Luban.EditorEnumItemInfo("HasItemTag", "", 2, "has item tag");
        public static readonly Luban.EditorEnumItemInfo HasBuild = new Luban.EditorEnumItemInfo("HasBuild", "", 3, "has build");
        public static readonly Luban.EditorEnumItemInfo HasQuality = new Luban.EditorEnumItemInfo("HasQuality", "", 4, "has quality");
        public static readonly Luban.EditorEnumItemInfo HasFlag = new Luban.EditorEnumItemInfo("HasFlag", "", 5, "has run flag");
        public static readonly Luban.EditorEnumItemInfo MissingFlag = new Luban.EditorEnumItemInfo("MissingFlag", "", 6, "missing run flag");
        public static readonly Luban.EditorEnumItemInfo MaxLives = new Luban.EditorEnumItemInfo("MaxLives", "", 7, "maximum lives");
        public static readonly Luban.EditorEnumItemInfo DayEquals = new Luban.EditorEnumItemInfo("DayEquals", "", 8, "exact day");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            MinCoins,
            HasItemTag,
            HasBuild,
            HasQuality,
            HasFlag,
            MissingFlag,
            MaxLives,
            DayEquals,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

