
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// event option outcome
    /// </summary>
    public enum BuqiEventOutcomeKind
    {
        /// <summary>
        /// gain coins
        /// </summary>
        Coins = 0,
        /// <summary>
        /// gain life
        /// </summary>
        Life = 1,
        /// <summary>
        /// grant item by constrained tag
        /// </summary>
        GrantItemTag = 2,
        /// <summary>
        /// grant refinement
        /// </summary>
        GrantRefinement = 3,
        /// <summary>
        /// upgrade item by tag
        /// </summary>
        UpgradeItemTag = 4,
        /// <summary>
        /// temporary haste
        /// </summary>
        TemporaryHaste = 5,
        /// <summary>
        /// temporary buffer
        /// </summary>
        TemporaryBuffer = 6,
        /// <summary>
        /// temporary healing
        /// </summary>
        TemporaryHealing = 7,
        /// <summary>
        /// next battle noise debt
        /// </summary>
        NoiseDebt = 8,
        /// <summary>
        /// free shop refresh
        /// </summary>
        FreeRefresh = 9,
        /// <summary>
        /// shop discount
        /// </summary>
        ShopDiscount = 10,
        /// <summary>
        /// set run flag
        /// </summary>
        SetFlag = 11,
        /// <summary>
        /// clear run flag
        /// </summary>
        ClearFlag = 12,
        /// <summary>
        /// remove item by tag
        /// </summary>
        RemoveItemTag = 13,
    }

    public static class BuqiEventOutcomeKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Coins = new Luban.EditorEnumItemInfo("Coins", "", 0, "gain coins");
        public static readonly Luban.EditorEnumItemInfo Life = new Luban.EditorEnumItemInfo("Life", "", 1, "gain life");
        public static readonly Luban.EditorEnumItemInfo GrantItemTag = new Luban.EditorEnumItemInfo("GrantItemTag", "", 2, "grant item by constrained tag");
        public static readonly Luban.EditorEnumItemInfo GrantRefinement = new Luban.EditorEnumItemInfo("GrantRefinement", "", 3, "grant refinement");
        public static readonly Luban.EditorEnumItemInfo UpgradeItemTag = new Luban.EditorEnumItemInfo("UpgradeItemTag", "", 4, "upgrade item by tag");
        public static readonly Luban.EditorEnumItemInfo TemporaryHaste = new Luban.EditorEnumItemInfo("TemporaryHaste", "", 5, "temporary haste");
        public static readonly Luban.EditorEnumItemInfo TemporaryBuffer = new Luban.EditorEnumItemInfo("TemporaryBuffer", "", 6, "temporary buffer");
        public static readonly Luban.EditorEnumItemInfo TemporaryHealing = new Luban.EditorEnumItemInfo("TemporaryHealing", "", 7, "temporary healing");
        public static readonly Luban.EditorEnumItemInfo NoiseDebt = new Luban.EditorEnumItemInfo("NoiseDebt", "", 8, "next battle noise debt");
        public static readonly Luban.EditorEnumItemInfo FreeRefresh = new Luban.EditorEnumItemInfo("FreeRefresh", "", 9, "free shop refresh");
        public static readonly Luban.EditorEnumItemInfo ShopDiscount = new Luban.EditorEnumItemInfo("ShopDiscount", "", 10, "shop discount");
        public static readonly Luban.EditorEnumItemInfo SetFlag = new Luban.EditorEnumItemInfo("SetFlag", "", 11, "set run flag");
        public static readonly Luban.EditorEnumItemInfo ClearFlag = new Luban.EditorEnumItemInfo("ClearFlag", "", 12, "clear run flag");
        public static readonly Luban.EditorEnumItemInfo RemoveItemTag = new Luban.EditorEnumItemInfo("RemoveItemTag", "", 13, "remove item by tag");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Coins,
            Life,
            GrantItemTag,
            GrantRefinement,
            UpgradeItemTag,
            TemporaryHaste,
            TemporaryBuffer,
            TemporaryHealing,
            NoiseDebt,
            FreeRefresh,
            ShopDiscount,
            SetFlag,
            ClearFlag,
            RemoveItemTag,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

