
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// event option outcome
/// </summary>
public sealed class BuqiEventOutcomeConfig :  Luban.EditorBeanBase 
{
    public BuqiEventOutcomeConfig()
    {
            Kind = BuqiEventOutcomeKind.Coins;
            Value = "";
            ReasonCode = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Kind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Kind = (BuqiEventOutcomeKind)System.Enum.Parse(typeof(BuqiEventOutcomeKind), _fieldJson); } else if(_fieldJson.IsNumber) { Kind = (BuqiEventOutcomeKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Amount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Amount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Value"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Value = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DurationDays"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  DurationDays = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ReasonCode"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ReasonCode = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Kind"] = new JSONNumber((int)Kind);
        }
        {
            _json["Amount"] = new JSONNumber(Amount);
        }
        {

            if (Value == null) { throw new System.ArgumentNullException(); }
            _json["Value"] = new JSONString(Value);
        }
        {
            _json["DurationDays"] = new JSONNumber(DurationDays);
        }
        {

            if (ReasonCode == null) { throw new System.ArgumentNullException(); }
            _json["ReasonCode"] = new JSONString(ReasonCode);
        }
    }

    public static BuqiEventOutcomeConfig LoadJsonBuqiEventOutcomeConfig(JSONNode _json)
    {
        BuqiEventOutcomeConfig obj = new BuqiEventOutcomeConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiEventOutcomeConfig(BuqiEventOutcomeConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// outcome kind
    /// </summary>
    public BuqiEventOutcomeKind Kind;

    /// <summary>
    /// outcome amount
    /// </summary>
    public int Amount;

    /// <summary>
    /// outcome qualifier
    /// </summary>
    public string Value;

    /// <summary>
    /// duration in days
    /// </summary>
    public int DurationDays;

    /// <summary>
    /// stable reason code
    /// </summary>
    public string ReasonCode;

}
}

