
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// 1 slot
    /// </summary>
    public enum BuqiSize
    {
        /// <summary>
        /// 1 slot
        /// </summary>
        S = 1,
        /// <summary>
        /// 2 slots
        /// </summary>
        M = 2,
        /// <summary>
        /// 3 slots
        /// </summary>
        L = 3,
    }

    public static class BuqiSize_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo S = new Luban.EditorEnumItemInfo("S", "", 1, "1 slot");
        public static readonly Luban.EditorEnumItemInfo M = new Luban.EditorEnumItemInfo("M", "", 2, "2 slots");
        public static readonly Luban.EditorEnumItemInfo L = new Luban.EditorEnumItemInfo("L", "", 3, "3 slots");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            S,
            M,
            L,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

