
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// merchant supply specialty
    /// </summary>
    public enum BuqiMerchantSpecialty
    {
        /// <summary>
        /// mixed item pool
        /// </summary>
        General = 0,
        /// <summary>
        /// non-weapon-only pool
        /// </summary>
        NonWeaponOnly = 1,
    }

    public static class BuqiMerchantSpecialty_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo General = new Luban.EditorEnumItemInfo("General", "", 0, "mixed item pool");
        public static readonly Luban.EditorEnumItemInfo NonWeaponOnly = new Luban.EditorEnumItemInfo("NonWeaponOnly", "", 1, "non-weapon-only pool");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            General,
            NonWeaponOnly,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

