
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// echo build snapshot
/// </summary>
public sealed class BuqiBuildSnapshotConfig :  Luban.EditorBeanBase 
{
    public BuqiBuildSnapshotConfig()
    {
            SnapshotId = "";
            ArchetypeId = BuqiBuild.fast;
            Items = new System.Collections.Generic.List<BuqiItemInstanceConfig>();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["SnapshotId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SnapshotId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ArchetypeId"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { ArchetypeId = (BuqiBuild)System.Enum.Parse(typeof(BuqiBuild), _fieldJson); } else if(_fieldJson.IsNumber) { ArchetypeId = (BuqiBuild)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["InitialExecution"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  InitialExecution = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InitialBuffer"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  InitialBuffer = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InitialNoiseDebt"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  InitialNoiseDebt = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Items"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Items = new System.Collections.Generic.List<BuqiItemInstanceConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiItemInstanceConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiItemInstanceConfig.LoadJsonBuqiItemInstanceConfig(__e0);  Items.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (SnapshotId == null) { throw new System.ArgumentNullException(); }
            _json["SnapshotId"] = new JSONString(SnapshotId);
        }
        {
            _json["ArchetypeId"] = new JSONNumber((int)ArchetypeId);
        }
        {
            _json["InitialExecution"] = new JSONNumber(InitialExecution);
        }
        {
            _json["InitialBuffer"] = new JSONNumber(InitialBuffer);
        }
        {
            _json["InitialNoiseDebt"] = new JSONNumber(InitialNoiseDebt);
        }
        {

            if (Items == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Items"] = __cjson0; foreach(var _e0 in Items) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiItemInstanceConfig.SaveJsonBuqiItemInstanceConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
    }

    public static BuqiBuildSnapshotConfig LoadJsonBuqiBuildSnapshotConfig(JSONNode _json)
    {
        BuqiBuildSnapshotConfig obj = new BuqiBuildSnapshotConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiBuildSnapshotConfig(BuqiBuildSnapshotConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// snapshot id
    /// </summary>
    public string SnapshotId;

    /// <summary>
    /// build archetype
    /// </summary>
    public BuqiBuild ArchetypeId;

    /// <summary>
    /// initial execution
    /// </summary>
    public int InitialExecution;

    /// <summary>
    /// initial buffer
    /// </summary>
    public int InitialBuffer;

    /// <summary>
    /// initial noise debt
    /// </summary>
    public int InitialNoiseDebt;

    /// <summary>
    /// board item instances
    /// </summary>
    public System.Collections.Generic.List<BuqiItemInstanceConfig> Items;

}
}

