
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// on use
    /// </summary>
    public enum BuqiTrigger
    {
        /// <summary>
        /// on use
        /// </summary>
        OnUse = 0,
        /// <summary>
        /// battle start
        /// </summary>
        OnBattleStart = 1,
        /// <summary>
        /// adjacent use
        /// </summary>
        OnAdjacentUse = 2,
        /// <summary>
        /// first condition
        /// </summary>
        OnFirstConditionMet = 3,
        /// <summary>
        /// use count
        /// </summary>
        OnUseCountReached = 4,
        /// <summary>
        /// first interfered
        /// </summary>
        OnFirstInterfered = 5,
    }

    public static class BuqiTrigger_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo OnUse = new Luban.EditorEnumItemInfo("OnUse", "", 0, "on use");
        public static readonly Luban.EditorEnumItemInfo OnBattleStart = new Luban.EditorEnumItemInfo("OnBattleStart", "", 1, "battle start");
        public static readonly Luban.EditorEnumItemInfo OnAdjacentUse = new Luban.EditorEnumItemInfo("OnAdjacentUse", "", 2, "adjacent use");
        public static readonly Luban.EditorEnumItemInfo OnFirstConditionMet = new Luban.EditorEnumItemInfo("OnFirstConditionMet", "", 3, "first condition");
        public static readonly Luban.EditorEnumItemInfo OnUseCountReached = new Luban.EditorEnumItemInfo("OnUseCountReached", "", 4, "use count");
        public static readonly Luban.EditorEnumItemInfo OnFirstInterfered = new Luban.EditorEnumItemInfo("OnFirstInterfered", "", 5, "first interfered");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            OnUse,
            OnBattleStart,
            OnAdjacentUse,
            OnFirstConditionMet,
            OnUseCountReached,
            OnFirstInterfered,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

