
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// event option cost
    /// </summary>
    public enum BuqiEventCostKind
    {
        /// <summary>
        /// no cost
        /// </summary>
        None = 0,
        /// <summary>
        /// coin cost
        /// </summary>
        Coins = 1,
        /// <summary>
        /// life cost
        /// </summary>
        Life = 2,
        /// <summary>
        /// remove item by tag
        /// </summary>
        ItemTag = 3,
        /// <summary>
        /// next battle noise debt
        /// </summary>
        NoiseDebt = 4,
    }

    public static class BuqiEventCostKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "", 0, "no cost");
        public static readonly Luban.EditorEnumItemInfo Coins = new Luban.EditorEnumItemInfo("Coins", "", 1, "coin cost");
        public static readonly Luban.EditorEnumItemInfo Life = new Luban.EditorEnumItemInfo("Life", "", 2, "life cost");
        public static readonly Luban.EditorEnumItemInfo ItemTag = new Luban.EditorEnumItemInfo("ItemTag", "", 3, "remove item by tag");
        public static readonly Luban.EditorEnumItemInfo NoiseDebt = new Luban.EditorEnumItemInfo("NoiseDebt", "", 4, "next battle noise debt");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            Coins,
            Life,
            ItemTag,
            NoiseDebt,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

