
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// formal supply category
    /// </summary>
    public enum BuqiItemCategory
    {
        /// <summary>
        /// invalid / missing classification
        /// </summary>
        Unknown = 0,
        /// <summary>
        /// non-weapon item
        /// </summary>
        NonWeapon = 1,
        /// <summary>
        /// formal weapon item
        /// </summary>
        Weapon = 2,
    }

    public static class BuqiItemCategory_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Unknown = new Luban.EditorEnumItemInfo("Unknown", "", 0, "invalid / missing classification");
        public static readonly Luban.EditorEnumItemInfo NonWeapon = new Luban.EditorEnumItemInfo("NonWeapon", "", 1, "non-weapon item");
        public static readonly Luban.EditorEnumItemInfo Weapon = new Luban.EditorEnumItemInfo("Weapon", "", 2, "formal weapon item");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Unknown,
            NonWeapon,
            Weapon,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

