
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// enemy execution
    /// </summary>
    public enum BuqiTarget
    {
        /// <summary>
        /// enemy execution
        /// </summary>
        EnemyExecution = 0,
        /// <summary>
        /// self
        /// </summary>
        Self = 1,
        /// <summary>
        /// left adjacent
        /// </summary>
        LeftAdjacentItem = 2,
        /// <summary>
        /// right adjacent
        /// </summary>
        RightAdjacentItem = 3,
        /// <summary>
        /// all adjacent
        /// </summary>
        AllAdjacentItems = 4,
        /// <summary>
        /// enemy shortest cooldown
        /// </summary>
        ShortestCooldownEnemyItem = 5,
        /// <summary>
        /// enemy longest cooldown
        /// </summary>
        LongestCooldownEnemyItem = 6,
        /// <summary>
        /// enemy leftmost
        /// </summary>
        LeftmostEnemyItem = 7,
        /// <summary>
        /// enemy rightmost
        /// </summary>
        RightmostEnemyItem = 8,
    }

    public static class BuqiTarget_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo EnemyExecution = new Luban.EditorEnumItemInfo("EnemyExecution", "", 0, "enemy execution");
        public static readonly Luban.EditorEnumItemInfo Self = new Luban.EditorEnumItemInfo("Self", "", 1, "self");
        public static readonly Luban.EditorEnumItemInfo LeftAdjacentItem = new Luban.EditorEnumItemInfo("LeftAdjacentItem", "", 2, "left adjacent");
        public static readonly Luban.EditorEnumItemInfo RightAdjacentItem = new Luban.EditorEnumItemInfo("RightAdjacentItem", "", 3, "right adjacent");
        public static readonly Luban.EditorEnumItemInfo AllAdjacentItems = new Luban.EditorEnumItemInfo("AllAdjacentItems", "", 4, "all adjacent");
        public static readonly Luban.EditorEnumItemInfo ShortestCooldownEnemyItem = new Luban.EditorEnumItemInfo("ShortestCooldownEnemyItem", "", 5, "enemy shortest cooldown");
        public static readonly Luban.EditorEnumItemInfo LongestCooldownEnemyItem = new Luban.EditorEnumItemInfo("LongestCooldownEnemyItem", "", 6, "enemy longest cooldown");
        public static readonly Luban.EditorEnumItemInfo LeftmostEnemyItem = new Luban.EditorEnumItemInfo("LeftmostEnemyItem", "", 7, "enemy leftmost");
        public static readonly Luban.EditorEnumItemInfo RightmostEnemyItem = new Luban.EditorEnumItemInfo("RightmostEnemyItem", "", 8, "enemy rightmost");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            EnemyExecution,
            Self,
            LeftAdjacentItem,
            RightAdjacentItem,
            AllAdjacentItems,
            ShortestCooldownEnemyItem,
            LongestCooldownEnemyItem,
            LeftmostEnemyItem,
            RightmostEnemyItem,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

