
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// damage
    /// </summary>
    public enum BuqiEffect
    {
        /// <summary>
        /// damage
        /// </summary>
        Damage = 0,
        /// <summary>
        /// buffer
        /// </summary>
        Buffer = 1,
        /// <summary>
        /// haste
        /// </summary>
        Haste = 2,
        /// <summary>
        /// delay
        /// </summary>
        Delay = 3,
        /// <summary>
        /// charge
        /// </summary>
        Charge = 4,
        /// <summary>
        /// noise
        /// </summary>
        Noise = 5,
    }

    public static class BuqiEffect_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Damage = new Luban.EditorEnumItemInfo("Damage", "", 0, "damage");
        public static readonly Luban.EditorEnumItemInfo Buffer = new Luban.EditorEnumItemInfo("Buffer", "", 1, "buffer");
        public static readonly Luban.EditorEnumItemInfo Haste = new Luban.EditorEnumItemInfo("Haste", "", 2, "haste");
        public static readonly Luban.EditorEnumItemInfo Delay = new Luban.EditorEnumItemInfo("Delay", "", 3, "delay");
        public static readonly Luban.EditorEnumItemInfo Charge = new Luban.EditorEnumItemInfo("Charge", "", 4, "charge");
        public static readonly Luban.EditorEnumItemInfo Noise = new Luban.EditorEnumItemInfo("Noise", "", 5, "noise");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Damage,
            Buffer,
            Haste,
            Delay,
            Charge,
            Noise,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

