
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// none
    /// </summary>
    public enum BuqiConditionKind
    {
        /// <summary>
        /// none
        /// </summary>
        None = 0,
        /// <summary>
        /// buffer lost
        /// </summary>
        BufferLost = 1,
        /// <summary>
        /// charge at least
        /// </summary>
        ChargeAtLeast = 2,
    }

    public static class BuqiConditionKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "", 0, "none");
        public static readonly Luban.EditorEnumItemInfo BufferLost = new Luban.EditorEnumItemInfo("BufferLost", "", 1, "buffer lost");
        public static readonly Luban.EditorEnumItemInfo ChargeAtLeast = new Luban.EditorEnumItemInfo("ChargeAtLeast", "", 2, "charge at least");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            BufferLost,
            ChargeAtLeast,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

