
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// single battle effect config
/// </summary>
public sealed class BuqiEffectConfig :  Luban.EditorBeanBase 
{
    public BuqiEffectConfig()
    {
            Trigger = BuqiTrigger.OnUse;
            Effect = BuqiEffect.Damage;
            Target = BuqiTarget.EnemyExecution;
            ReasonCode = "";
            ConditionKind = BuqiConditionKind.None;
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Trigger"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Trigger = (BuqiTrigger)System.Enum.Parse(typeof(BuqiTrigger), _fieldJson); } else if(_fieldJson.IsNumber) { Trigger = (BuqiTrigger)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Effect"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Effect = (BuqiEffect)System.Enum.Parse(typeof(BuqiEffect), _fieldJson); } else if(_fieldJson.IsNumber) { Effect = (BuqiEffect)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Target"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Target = (BuqiTarget)System.Enum.Parse(typeof(BuqiTarget), _fieldJson); } else if(_fieldJson.IsNumber) { Target = (BuqiTarget)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Amount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Amount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DurationTicks"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  DurationTicks = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ReasonCode"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ReasonCode = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ConditionKind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { ConditionKind = (BuqiConditionKind)System.Enum.Parse(typeof(BuqiConditionKind), _fieldJson); } else if(_fieldJson.IsNumber) { ConditionKind = (BuqiConditionKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["ConditionThreshold"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  ConditionThreshold = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["UseCountThreshold"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  UseCountThreshold = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ChargeReadLimit"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  ChargeReadLimit = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AmountPerCharge"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  AmountPerCharge = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ChargeConsume"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsBoolean) { throw new SerializationException(); }  ChargeConsume = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ResetCountOnReached"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsBoolean) { throw new SerializationException(); }  ResetCountOnReached = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Trigger"] = new JSONNumber((int)Trigger);
        }
        {
            _json["Effect"] = new JSONNumber((int)Effect);
        }
        {
            _json["Target"] = new JSONNumber((int)Target);
        }
        {
            _json["Amount"] = new JSONNumber(Amount);
        }
        {
            _json["DurationTicks"] = new JSONNumber(DurationTicks);
        }
        {

            if (ReasonCode == null) { throw new System.ArgumentNullException(); }
            _json["ReasonCode"] = new JSONString(ReasonCode);
        }
        {
            _json["ConditionKind"] = new JSONNumber((int)ConditionKind);
        }
        {
            _json["ConditionThreshold"] = new JSONNumber(ConditionThreshold);
        }
        {
            _json["UseCountThreshold"] = new JSONNumber(UseCountThreshold);
        }
        {
            _json["ChargeReadLimit"] = new JSONNumber(ChargeReadLimit);
        }
        {
            _json["AmountPerCharge"] = new JSONNumber(AmountPerCharge);
        }
        {
            _json["ChargeConsume"] = new JSONBool(ChargeConsume);
        }
        {
            _json["ResetCountOnReached"] = new JSONBool(ResetCountOnReached);
        }
    }

    public static BuqiEffectConfig LoadJsonBuqiEffectConfig(JSONNode _json)
    {
        BuqiEffectConfig obj = new BuqiEffectConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiEffectConfig(BuqiEffectConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// trigger
    /// </summary>
    public BuqiTrigger Trigger;

    /// <summary>
    /// effect
    /// </summary>
    public BuqiEffect Effect;

    /// <summary>
    /// target
    /// </summary>
    public BuqiTarget Target;

    /// <summary>
    /// amount
    /// </summary>
    public int Amount;

    /// <summary>
    /// duration ticks
    /// </summary>
    public int DurationTicks;

    /// <summary>
    /// stable reason code
    /// </summary>
    public string ReasonCode;

    /// <summary>
    /// condition kind
    /// </summary>
    public BuqiConditionKind ConditionKind;

    /// <summary>
    /// condition threshold
    /// </summary>
    public int ConditionThreshold;

    /// <summary>
    /// use count threshold
    /// </summary>
    public int UseCountThreshold;

    /// <summary>
    /// charge read limit
    /// </summary>
    public int ChargeReadLimit;

    /// <summary>
    /// amount per charge
    /// </summary>
    public int AmountPerCharge;

    /// <summary>
    /// consume charge
    /// </summary>
    public bool ChargeConsume;

    /// <summary>
    /// reset count
    /// </summary>
    public bool ResetCountOnReached;

}
}

