
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// echo board item instance
/// </summary>
public sealed class BuqiItemInstanceConfig :  Luban.EditorBeanBase 
{
    public BuqiItemInstanceConfig()
    {
            InstanceId = "";
            DefinitionId = "";
            Quality = BuqiQuality.Normal;
            RefinementId = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["InstanceId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  InstanceId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DefinitionId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DefinitionId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Quality"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Quality = (BuqiQuality)System.Enum.Parse(typeof(BuqiQuality), _fieldJson); } else if(_fieldJson.IsNumber) { Quality = (BuqiQuality)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["AnchorSlot"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  AnchorSlot = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RefinementId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  RefinementId = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (InstanceId == null) { throw new System.ArgumentNullException(); }
            _json["InstanceId"] = new JSONString(InstanceId);
        }
        {

            if (DefinitionId == null) { throw new System.ArgumentNullException(); }
            _json["DefinitionId"] = new JSONString(DefinitionId);
        }
        {
            _json["Quality"] = new JSONNumber((int)Quality);
        }
        {
            _json["AnchorSlot"] = new JSONNumber(AnchorSlot);
        }
        {

            if (RefinementId == null) { throw new System.ArgumentNullException(); }
            _json["RefinementId"] = new JSONString(RefinementId);
        }
    }

    public static BuqiItemInstanceConfig LoadJsonBuqiItemInstanceConfig(JSONNode _json)
    {
        BuqiItemInstanceConfig obj = new BuqiItemInstanceConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiItemInstanceConfig(BuqiItemInstanceConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// instance id
    /// </summary>
    public string InstanceId;

    /// <summary>
    /// item id
    /// </summary>
    public string DefinitionId;

    /// <summary>
    /// quality
    /// </summary>
    public BuqiQuality Quality;

    /// <summary>
    /// anchor slot
    /// </summary>
    public int AnchorSlot;

    /// <summary>
    /// refinement id
    /// </summary>
    public string RefinementId;

}
}

