
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// run-layer effect
    /// </summary>
    public enum BuqiRunEffect
    {
        /// <summary>
        /// gain coin
        /// </summary>
        GainCoin = 0,
        /// <summary>
        /// discount coin
        /// </summary>
        DiscountCoin = 1,
    }

    public static class BuqiRunEffect_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo GainCoin = new Luban.EditorEnumItemInfo("GainCoin", "", 0, "gain coin");
        public static readonly Luban.EditorEnumItemInfo DiscountCoin = new Luban.EditorEnumItemInfo("DiscountCoin", "", 1, "discount coin");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            GainCoin,
            DiscountCoin,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

