
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// merchant offer slot constraint
/// </summary>
public sealed class BuqiMerchantSlotConfig :  Luban.EditorBeanBase 
{
    public BuqiMerchantSlotConfig()
    {
            SlotId = "";
            SlotKind = BuqiMerchantSlotKind.Archetype;
            BuildFilter = "";
            SizeFilter = "";
            QualityFilter = "";
            RequiredTag = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["SlotId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SlotId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SlotKind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { SlotKind = (BuqiMerchantSlotKind)System.Enum.Parse(typeof(BuqiMerchantSlotKind), _fieldJson); } else if(_fieldJson.IsNumber) { SlotKind = (BuqiMerchantSlotKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["BuildFilter"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  BuildFilter = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SizeFilter"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SizeFilter = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["QualityFilter"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  QualityFilter = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RequiredTag"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  RequiredTag = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MinUnlockDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MinUnlockDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxUnlockDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxUnlockDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Weight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Weight = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Count"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Count = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (SlotId == null) { throw new System.ArgumentNullException(); }
            _json["SlotId"] = new JSONString(SlotId);
        }
        {
            _json["SlotKind"] = new JSONNumber((int)SlotKind);
        }
        {

            if (BuildFilter == null) { throw new System.ArgumentNullException(); }
            _json["BuildFilter"] = new JSONString(BuildFilter);
        }
        {

            if (SizeFilter == null) { throw new System.ArgumentNullException(); }
            _json["SizeFilter"] = new JSONString(SizeFilter);
        }
        {

            if (QualityFilter == null) { throw new System.ArgumentNullException(); }
            _json["QualityFilter"] = new JSONString(QualityFilter);
        }
        {

            if (RequiredTag == null) { throw new System.ArgumentNullException(); }
            _json["RequiredTag"] = new JSONString(RequiredTag);
        }
        {
            _json["MinUnlockDay"] = new JSONNumber(MinUnlockDay);
        }
        {
            _json["MaxUnlockDay"] = new JSONNumber(MaxUnlockDay);
        }
        {
            _json["Weight"] = new JSONNumber(Weight);
        }
        {
            _json["Count"] = new JSONNumber(Count);
        }
    }

    public static BuqiMerchantSlotConfig LoadJsonBuqiMerchantSlotConfig(JSONNode _json)
    {
        BuqiMerchantSlotConfig obj = new BuqiMerchantSlotConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiMerchantSlotConfig(BuqiMerchantSlotConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// slot id
    /// </summary>
    public string SlotId;

    /// <summary>
    /// slot kind
    /// </summary>
    public BuqiMerchantSlotKind SlotKind;

    /// <summary>
    /// plus separated builds
    /// </summary>
    public string BuildFilter;

    /// <summary>
    /// plus separated sizes
    /// </summary>
    public string SizeFilter;

    /// <summary>
    /// plus separated qualities
    /// </summary>
    public string QualityFilter;

    /// <summary>
    /// required tag
    /// </summary>
    public string RequiredTag;

    /// <summary>
    /// minimum item unlock day
    /// </summary>
    public int MinUnlockDay;

    /// <summary>
    /// maximum item unlock day
    /// </summary>
    public int MaxUnlockDay;

    /// <summary>
    /// slot weight
    /// </summary>
    public int Weight;

    /// <summary>
    /// offer count
    /// </summary>
    public int Count;

}
}

