
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// fast execution
    /// </summary>
    public enum BuqiBuild
    {
        /// <summary>
        /// fast execution
        /// </summary>
        fast = 1,
        /// <summary>
        /// buffer counter
        /// </summary>
        buffer = 2,
        /// <summary>
        /// chain engine
        /// </summary>
        chain = 3,
    }

    public static class BuqiBuild_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo fast = new Luban.EditorEnumItemInfo("fast", "Fast", 1, "fast execution");
        public static readonly Luban.EditorEnumItemInfo buffer = new Luban.EditorEnumItemInfo("buffer", "BufferCounter", 2, "buffer counter");
        public static readonly Luban.EditorEnumItemInfo chain = new Luban.EditorEnumItemInfo("chain", "Chain", 3, "chain engine");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            fast,
            buffer,
            chain,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

