
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// merchant constrained slot
    /// </summary>
    public enum BuqiMerchantSlotKind
    {
        /// <summary>
        /// build filter
        /// </summary>
        Archetype = 0,
        /// <summary>
        /// size filter
        /// </summary>
        Size = 1,
        /// <summary>
        /// quality filter
        /// </summary>
        Quality = 2,
        /// <summary>
        /// day stage filter
        /// </summary>
        Stage = 3,
        /// <summary>
        /// bridge slot
        /// </summary>
        Bridge = 4,
        /// <summary>
        /// counter slot
        /// </summary>
        Counter = 5,
        /// <summary>
        /// economy slot
        /// </summary>
        Economy = 6,
    }

    public static class BuqiMerchantSlotKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Archetype = new Luban.EditorEnumItemInfo("Archetype", "", 0, "build filter");
        public static readonly Luban.EditorEnumItemInfo Size = new Luban.EditorEnumItemInfo("Size", "", 1, "size filter");
        public static readonly Luban.EditorEnumItemInfo Quality = new Luban.EditorEnumItemInfo("Quality", "", 2, "quality filter");
        public static readonly Luban.EditorEnumItemInfo Stage = new Luban.EditorEnumItemInfo("Stage", "", 3, "day stage filter");
        public static readonly Luban.EditorEnumItemInfo Bridge = new Luban.EditorEnumItemInfo("Bridge", "", 4, "bridge slot");
        public static readonly Luban.EditorEnumItemInfo Counter = new Luban.EditorEnumItemInfo("Counter", "", 5, "counter slot");
        public static readonly Luban.EditorEnumItemInfo Economy = new Luban.EditorEnumItemInfo("Economy", "", 6, "economy slot");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Archetype,
            Size,
            Quality,
            Stage,
            Bridge,
            Counter,
            Economy,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

