
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// run-layer trigger
    /// </summary>
    public enum BuqiRunTrigger
    {
        /// <summary>
        /// no trigger
        /// </summary>
        None = 0,
        /// <summary>
        /// battle-end damage threshold
        /// </summary>
        OnBattleEndDamage = 1,
        /// <summary>
        /// battle-end effective buffer threshold
        /// </summary>
        OnBattleEndBufferAbsorbed = 2,
        /// <summary>
        /// battle-end effective healing threshold
        /// </summary>
        OnBattleEndHealing = 3,
        /// <summary>
        /// first purchase or upgrade per day
        /// </summary>
        OnFirstPurchaseOrUpgrade = 4,
    }

    public static class BuqiRunTrigger_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "", 0, "no trigger");
        public static readonly Luban.EditorEnumItemInfo OnBattleEndDamage = new Luban.EditorEnumItemInfo("OnBattleEndDamage", "", 1, "battle-end damage threshold");
        public static readonly Luban.EditorEnumItemInfo OnBattleEndBufferAbsorbed = new Luban.EditorEnumItemInfo("OnBattleEndBufferAbsorbed", "", 2, "battle-end effective buffer threshold");
        public static readonly Luban.EditorEnumItemInfo OnBattleEndHealing = new Luban.EditorEnumItemInfo("OnBattleEndHealing", "", 3, "battle-end effective healing threshold");
        public static readonly Luban.EditorEnumItemInfo OnFirstPurchaseOrUpgrade = new Luban.EditorEnumItemInfo("OnFirstPurchaseOrUpgrade", "", 4, "first purchase or upgrade per day");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            OnBattleEndDamage,
            OnBattleEndBufferAbsorbed,
            OnBattleEndHealing,
            OnFirstPurchaseOrUpgrade,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

