
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// battle effect
    /// </summary>
    public enum BuqiEffect
    {
        /// <summary>
        /// attack
        /// </summary>
        Damage = 0,
        /// <summary>
        /// shield
        /// </summary>
        Buffer = 1,
        /// <summary>
        /// haste
        /// </summary>
        Haste = 2,
        /// <summary>
        /// slow
        /// </summary>
        Delay = 3,
        /// <summary>
        /// charge
        /// </summary>
        Charge = 4,
        /// <summary>
        /// overload
        /// </summary>
        Noise = 5,
        /// <summary>
        /// heal
        /// </summary>
        Heal = 6,
        /// <summary>
        /// life regen
        /// </summary>
        Regen = 7,
        /// <summary>
        /// poison
        /// </summary>
        Poison = 8,
        /// <summary>
        /// burn
        /// </summary>
        Burn = 9,
        /// <summary>
        /// freeze
        /// </summary>
        Freeze = 10,
        /// <summary>
        /// ammo refill
        /// </summary>
        Ammo = 11,
        /// <summary>
        /// enter or leave flight
        /// </summary>
        Flight = 12,
        /// <summary>
        /// rage accumulation
        /// </summary>
        Rage = 13,
    }

    public static class BuqiEffect_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Damage = new Luban.EditorEnumItemInfo("Damage", "", 0, "attack");
        public static readonly Luban.EditorEnumItemInfo Buffer = new Luban.EditorEnumItemInfo("Buffer", "", 1, "shield");
        public static readonly Luban.EditorEnumItemInfo Haste = new Luban.EditorEnumItemInfo("Haste", "", 2, "haste");
        public static readonly Luban.EditorEnumItemInfo Delay = new Luban.EditorEnumItemInfo("Delay", "", 3, "slow");
        public static readonly Luban.EditorEnumItemInfo Charge = new Luban.EditorEnumItemInfo("Charge", "", 4, "charge");
        public static readonly Luban.EditorEnumItemInfo Noise = new Luban.EditorEnumItemInfo("Noise", "", 5, "overload");
        public static readonly Luban.EditorEnumItemInfo Heal = new Luban.EditorEnumItemInfo("Heal", "", 6, "heal");
        public static readonly Luban.EditorEnumItemInfo Regen = new Luban.EditorEnumItemInfo("Regen", "", 7, "life regen");
        public static readonly Luban.EditorEnumItemInfo Poison = new Luban.EditorEnumItemInfo("Poison", "", 8, "poison");
        public static readonly Luban.EditorEnumItemInfo Burn = new Luban.EditorEnumItemInfo("Burn", "", 9, "burn");
        public static readonly Luban.EditorEnumItemInfo Freeze = new Luban.EditorEnumItemInfo("Freeze", "", 10, "freeze");
        public static readonly Luban.EditorEnumItemInfo Ammo = new Luban.EditorEnumItemInfo("Ammo", "", 11, "ammo refill");
        public static readonly Luban.EditorEnumItemInfo Flight = new Luban.EditorEnumItemInfo("Flight", "", 12, "enter or leave flight");
        public static readonly Luban.EditorEnumItemInfo Rage = new Luban.EditorEnumItemInfo("Rage", "", 13, "rage accumulation");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Damage,
            Buffer,
            Haste,
            Delay,
            Charge,
            Noise,
            Heal,
            Regen,
            Poison,
            Burn,
            Freeze,
            Ammo,
            Flight,
            Rage,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

