
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Hot.Editor
{
    /// <summary>
    /// training project effect
    /// </summary>
    public enum BuqiTrainingEffectKind
    {
        /// <summary>
        /// cooldown percentage
        /// </summary>
        CooldownPercent = 0,
        /// <summary>
        /// opening haste
        /// </summary>
        OpeningHaste = 1,
        /// <summary>
        /// adjacent haste
        /// </summary>
        AdjacentHaste = 2,
        /// <summary>
        /// opening buffer
        /// </summary>
        OpeningBuffer = 3,
        /// <summary>
        /// buffer gain percentage
        /// </summary>
        BufferGainPercent = 4,
        /// <summary>
        /// first interference ward
        /// </summary>
        FirstInterferenceWard = 5,
        /// <summary>
        /// opening heal
        /// </summary>
        OpeningHeal = 6,
        /// <summary>
        /// healing percentage
        /// </summary>
        HealingPercent = 7,
        /// <summary>
        /// regen duration
        /// </summary>
        RegenDuration = 8,
        /// <summary>
        /// upgrade discount
        /// </summary>
        UpgradeDiscount = 9,
        /// <summary>
        /// refinement discount
        /// </summary>
        RefinementDiscount = 10,
        /// <summary>
        /// free shop reroll
        /// </summary>
        ShopReroll = 11,
    }

    public static class BuqiTrainingEffectKind_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo CooldownPercent = new Luban.EditorEnumItemInfo("CooldownPercent", "", 0, "cooldown percentage");
        public static readonly Luban.EditorEnumItemInfo OpeningHaste = new Luban.EditorEnumItemInfo("OpeningHaste", "", 1, "opening haste");
        public static readonly Luban.EditorEnumItemInfo AdjacentHaste = new Luban.EditorEnumItemInfo("AdjacentHaste", "", 2, "adjacent haste");
        public static readonly Luban.EditorEnumItemInfo OpeningBuffer = new Luban.EditorEnumItemInfo("OpeningBuffer", "", 3, "opening buffer");
        public static readonly Luban.EditorEnumItemInfo BufferGainPercent = new Luban.EditorEnumItemInfo("BufferGainPercent", "", 4, "buffer gain percentage");
        public static readonly Luban.EditorEnumItemInfo FirstInterferenceWard = new Luban.EditorEnumItemInfo("FirstInterferenceWard", "", 5, "first interference ward");
        public static readonly Luban.EditorEnumItemInfo OpeningHeal = new Luban.EditorEnumItemInfo("OpeningHeal", "", 6, "opening heal");
        public static readonly Luban.EditorEnumItemInfo HealingPercent = new Luban.EditorEnumItemInfo("HealingPercent", "", 7, "healing percentage");
        public static readonly Luban.EditorEnumItemInfo RegenDuration = new Luban.EditorEnumItemInfo("RegenDuration", "", 8, "regen duration");
        public static readonly Luban.EditorEnumItemInfo UpgradeDiscount = new Luban.EditorEnumItemInfo("UpgradeDiscount", "", 9, "upgrade discount");
        public static readonly Luban.EditorEnumItemInfo RefinementDiscount = new Luban.EditorEnumItemInfo("RefinementDiscount", "", 10, "refinement discount");
        public static readonly Luban.EditorEnumItemInfo ShopReroll = new Luban.EditorEnumItemInfo("ShopReroll", "", 11, "free shop reroll");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            CooldownPercent,
            OpeningHaste,
            AdjacentHaste,
            OpeningBuffer,
            BufferGainPercent,
            FirstInterferenceWard,
            OpeningHeal,
            HealingPercent,
            RegenDuration,
            UpgradeDiscount,
            RefinementDiscount,
            ShopReroll,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

