
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// event option cost
/// </summary>
public sealed class BuqiEventCostConfig :  Luban.EditorBeanBase 
{
    public BuqiEventCostConfig()
    {
            Kind = BuqiEventCostKind.None;
            Value = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Kind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Kind = (BuqiEventCostKind)System.Enum.Parse(typeof(BuqiEventCostKind), _fieldJson); } else if(_fieldJson.IsNumber) { Kind = (BuqiEventCostKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Amount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Amount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Value"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Value = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Kind"] = new JSONNumber((int)Kind);
        }
        {
            _json["Amount"] = new JSONNumber(Amount);
        }
        {

            if (Value == null) { throw new System.ArgumentNullException(); }
            _json["Value"] = new JSONString(Value);
        }
    }

    public static BuqiEventCostConfig LoadJsonBuqiEventCostConfig(JSONNode _json)
    {
        BuqiEventCostConfig obj = new BuqiEventCostConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiEventCostConfig(BuqiEventCostConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// cost kind
    /// </summary>
    public BuqiEventCostKind Kind;

    /// <summary>
    /// cost amount
    /// </summary>
    public int Amount;

    /// <summary>
    /// cost qualifier
    /// </summary>
    public string Value;

}
}

