
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

/// <summary>
/// run-layer item effect
/// </summary>
public sealed class BuqiRunEffectConfig :  Luban.EditorBeanBase 
{
    public BuqiRunEffectConfig()
    {
            Trigger = BuqiRunTrigger.None;
            Effect = BuqiRunEffect.GainCoin;
            ReasonCode = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Trigger"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Trigger = (BuqiRunTrigger)System.Enum.Parse(typeof(BuqiRunTrigger), _fieldJson); } else if(_fieldJson.IsNumber) { Trigger = (BuqiRunTrigger)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Effect"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Effect = (BuqiRunEffect)System.Enum.Parse(typeof(BuqiRunEffect), _fieldJson); } else if(_fieldJson.IsNumber) { Effect = (BuqiRunEffect)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Amount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Amount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Threshold"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Threshold = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxPerDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxPerDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ReasonCode"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ReasonCode = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Trigger"] = new JSONNumber((int)Trigger);
        }
        {
            _json["Effect"] = new JSONNumber((int)Effect);
        }
        {
            _json["Amount"] = new JSONNumber(Amount);
        }
        {
            _json["Threshold"] = new JSONNumber(Threshold);
        }
        {
            _json["MaxPerDay"] = new JSONNumber(MaxPerDay);
        }
        {

            if (ReasonCode == null) { throw new System.ArgumentNullException(); }
            _json["ReasonCode"] = new JSONString(ReasonCode);
        }
    }

    public static BuqiRunEffectConfig LoadJsonBuqiRunEffectConfig(JSONNode _json)
    {
        BuqiRunEffectConfig obj = new BuqiRunEffectConfig();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuqiRunEffectConfig(BuqiRunEffectConfig _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// run trigger
    /// </summary>
    public BuqiRunTrigger Trigger;

    /// <summary>
    /// run effect
    /// </summary>
    public BuqiRunEffect Effect;

    /// <summary>
    /// effect amount
    /// </summary>
    public int Amount;

    /// <summary>
    /// trigger threshold
    /// </summary>
    public int Threshold;

    /// <summary>
    /// daily cap
    /// </summary>
    public int MaxPerDay;

    /// <summary>
    /// stable reason code
    /// </summary>
    public string ReasonCode;

}
}

