
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuff :  Luban.EditorBeanBase 
{
    public DRBuff()
    {
            BuffType = BulletBuffType.Seeking;
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Duration"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Duration = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BuffType"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { BuffType = (BulletBuffType)System.Enum.Parse(typeof(BulletBuffType), _fieldJson); } else if(_fieldJson.IsNumber) { BuffType = (BulletBuffType)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["Duration"] = new JSONNumber(Duration);
        }
        {
            _json["BuffType"] = new JSONNumber((int)BuffType);
        }
    }

    public static DRBuff LoadJsonDRBuff(SimpleJSON.JSONNode _json)
    {
        DRBuff obj = new DRBuff();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuff(DRBuff _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// Buff编号
    /// </summary>
    public int Id;

    /// <summary>
    /// 持续时间
    /// </summary>
    public float Duration;

    /// <summary>
    /// Buff类型
    /// </summary>
    public BulletBuffType BuffType;

}

}

