
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiItem :  Luban.EditorBeanBase 
{
    public DRBuqiItem()
    {
            DefinitionId = "";
            DisplayName = "";
            DesignNote = "";
            EffectDescription = "";
            Size = BuqiSize.S;
            ArchetypeId = BuqiBuild.fast;
            Tags = new System.Collections.Generic.List<string>();
            Effects = new System.Collections.Generic.List<BuqiEffectConfig>();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["DefinitionId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DefinitionId = _fieldJson;
            }
        }

        {
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }

        {
            var _fieldJson = _json["DesignNote"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DesignNote = _fieldJson;
            }
        }

        {
            var _fieldJson = _json["EffectDescription"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EffectDescription = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Size"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Size = (BuqiSize)System.Enum.Parse(typeof(BuqiSize), _fieldJson); } else if(_fieldJson.IsNumber) { Size = (BuqiSize)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["BasePrice"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BasePrice = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BaseCooldownTicks"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BaseCooldownTicks = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ArchetypeId"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { ArchetypeId = (BuqiBuild)System.Enum.Parse(typeof(BuqiBuild), _fieldJson); } else if(_fieldJson.IsNumber) { ArchetypeId = (BuqiBuild)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Tags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  Tags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Effects"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<BuqiEffectConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiEffectConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiEffectConfig.LoadJsonBuqiEffectConfig(__e0);  Effects.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (DefinitionId == null) { throw new System.ArgumentNullException(); }
            _json["DefinitionId"] = new JSONString(DefinitionId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (DesignNote == null) { throw new System.ArgumentNullException(); }
            _json["DesignNote"] = new JSONString(DesignNote);
        }
        {

            if (EffectDescription == null) { throw new System.ArgumentNullException(); }
            _json["EffectDescription"] = new JSONString(EffectDescription);
        }
        {
            _json["Size"] = new JSONNumber((int)Size);
        }
        {
            _json["BasePrice"] = new JSONNumber(BasePrice);
        }
        {
            _json["BaseCooldownTicks"] = new JSONNumber(BaseCooldownTicks);
        }
        {
            _json["ArchetypeId"] = new JSONNumber((int)ArchetypeId);
        }
        {

            if (Tags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Tags"] = __cjson0; foreach(var _e0 in Tags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (Effects == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Effects"] = __cjson0; foreach(var _e0 in Effects) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiEffectConfig.SaveJsonBuqiEffectConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
    }

    public static DRBuqiItem LoadJsonDRBuqiItem(JSONNode _json)
    {
        DRBuqiItem obj = new DRBuqiItem();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiItem(DRBuqiItem _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// item id
    /// </summary>
    public string DefinitionId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// planner-only Chinese usage note
    /// </summary>
    public string DesignNote;

    /// <summary>
    /// formal in-game effect description
    /// </summary>
    public string EffectDescription;

    /// <summary>
    /// size
    /// </summary>
    public BuqiSize Size;

    /// <summary>
    /// price
    /// </summary>
    public int BasePrice;

    /// <summary>
    /// cooldown ticks
    /// </summary>
    public int BaseCooldownTicks;

    /// <summary>
    /// build
    /// </summary>
    public BuqiBuild ArchetypeId;

    /// <summary>
    /// tags
    /// </summary>
    public System.Collections.Generic.List<string> Tags;

    /// <summary>
    /// effect list
    /// </summary>
    public System.Collections.Generic.List<BuqiEffectConfig> Effects;

}
}

