
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiEcho :  Luban.EditorBeanBase 
{
    public DRBuqiEcho()
    {
            EchoId = "";
            DisplayName = "";
            Tier = "";
            Build = BuqiBuild.fast;
            Snapshot = new BuqiBuildSnapshotConfig();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["EchoId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EchoId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Tier"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Tier = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Build"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Build = (BuqiBuild)System.Enum.Parse(typeof(BuqiBuild), _fieldJson); } else if(_fieldJson.IsNumber) { Build = (BuqiBuild)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Snapshot"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsObject) { throw new SerializationException(); }  Snapshot = BuqiBuildSnapshotConfig.LoadJsonBuqiBuildSnapshotConfig(_fieldJson);
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (EchoId == null) { throw new System.ArgumentNullException(); }
            _json["EchoId"] = new JSONString(EchoId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (Tier == null) { throw new System.ArgumentNullException(); }
            _json["Tier"] = new JSONString(Tier);
        }
        {
            _json["Build"] = new JSONNumber((int)Build);
        }
        {
            { var __bjson0 = new JSONObject(); _json["Snapshot"] = __bjson0; BuqiBuildSnapshotConfig.SaveJsonBuqiBuildSnapshotConfig(Snapshot, __bjson0); }
        }
    }

    public static DRBuqiEcho LoadJsonDRBuqiEcho(JSONNode _json)
    {
        DRBuqiEcho obj = new DRBuqiEcho();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiEcho(DRBuqiEcho _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// echo id
    /// </summary>
    public string EchoId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// tier
    /// </summary>
    public string Tier;

    /// <summary>
    /// build
    /// </summary>
    public BuqiBuild Build;

    /// <summary>
    /// build snapshot
    /// </summary>
    public BuqiBuildSnapshotConfig Snapshot;

}
}

