
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiTrainer :  Luban.EditorBeanBase 
{
    public DRBuqiTrainer()
    {
            TrainerId = "";
            DisplayName = "";
            LocalizationKey = "";
            ProjectIds = new System.Collections.Generic.List<string>();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["TrainerId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  TrainerId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MinDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MinDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Weight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Weight = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ProjectIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ProjectIds = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  ProjectIds.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (TrainerId == null) { throw new System.ArgumentNullException(); }
            _json["TrainerId"] = new JSONString(TrainerId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["MinDay"] = new JSONNumber(MinDay);
        }
        {
            _json["MaxDay"] = new JSONNumber(MaxDay);
        }
        {
            _json["Weight"] = new JSONNumber(Weight);
        }
        {

            if (ProjectIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ProjectIds"] = __cjson0; foreach(var _e0 in ProjectIds) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
    }

    public static DRBuqiTrainer LoadJsonDRBuqiTrainer(JSONNode _json)
    {
        DRBuqiTrainer obj = new DRBuqiTrainer();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiTrainer(DRBuqiTrainer _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// trainer id
    /// </summary>
    public string TrainerId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// localization key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// minimum day
    /// </summary>
    public int MinDay;

    /// <summary>
    /// maximum day
    /// </summary>
    public int MaxDay;

    /// <summary>
    /// selection weight
    /// </summary>
    public int Weight;

    /// <summary>
    /// training projects
    /// </summary>
    public System.Collections.Generic.List<string> ProjectIds;

}
}

