
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiTrainingProject :  Luban.EditorBeanBase 
{
    public DRBuqiTrainingProject()
    {
            ProjectId = "";
            TrainerId = "";
            DisplayName = "";
            LocalizationKey = "";
            RequiredTag = "";
            ExcludedTag = "";
            EffectKind = BuqiTrainingEffectKind.CooldownPercent;
            Summary = "";
            SummaryLocalizationKey = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["ProjectId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ProjectId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["TrainerId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  TrainerId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MinDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MinDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Cost"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Cost = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RequiredTag"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  RequiredTag = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ExcludedTag"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ExcludedTag = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["EffectKind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { EffectKind = (BuqiTrainingEffectKind)System.Enum.Parse(typeof(BuqiTrainingEffectKind), _fieldJson); } else if(_fieldJson.IsNumber) { EffectKind = (BuqiTrainingEffectKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Amount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Amount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Duration"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Duration = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxPerRun"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxPerRun = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Summary"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Summary = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SummaryLocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SummaryLocalizationKey = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (ProjectId == null) { throw new System.ArgumentNullException(); }
            _json["ProjectId"] = new JSONString(ProjectId);
        }
        {

            if (TrainerId == null) { throw new System.ArgumentNullException(); }
            _json["TrainerId"] = new JSONString(TrainerId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["MinDay"] = new JSONNumber(MinDay);
        }
        {
            _json["MaxDay"] = new JSONNumber(MaxDay);
        }
        {
            _json["Cost"] = new JSONNumber(Cost);
        }
        {

            if (RequiredTag == null) { throw new System.ArgumentNullException(); }
            _json["RequiredTag"] = new JSONString(RequiredTag);
        }
        {

            if (ExcludedTag == null) { throw new System.ArgumentNullException(); }
            _json["ExcludedTag"] = new JSONString(ExcludedTag);
        }
        {
            _json["EffectKind"] = new JSONNumber((int)EffectKind);
        }
        {
            _json["Amount"] = new JSONNumber(Amount);
        }
        {
            _json["Duration"] = new JSONNumber(Duration);
        }
        {
            _json["MaxPerRun"] = new JSONNumber(MaxPerRun);
        }
        {

            if (Summary == null) { throw new System.ArgumentNullException(); }
            _json["Summary"] = new JSONString(Summary);
        }
        {

            if (SummaryLocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["SummaryLocalizationKey"] = new JSONString(SummaryLocalizationKey);
        }
    }

    public static DRBuqiTrainingProject LoadJsonDRBuqiTrainingProject(JSONNode _json)
    {
        DRBuqiTrainingProject obj = new DRBuqiTrainingProject();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiTrainingProject(DRBuqiTrainingProject _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// project id
    /// </summary>
    public string ProjectId;

    /// <summary>
    /// trainer id
    /// </summary>
    public string TrainerId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// localization key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// minimum day
    /// </summary>
    public int MinDay;

    /// <summary>
    /// maximum day
    /// </summary>
    public int MaxDay;

    /// <summary>
    /// coin cost
    /// </summary>
    public int Cost;

    /// <summary>
    /// required item tag
    /// </summary>
    public string RequiredTag;

    /// <summary>
    /// excluded item tag
    /// </summary>
    public string ExcludedTag;

    /// <summary>
    /// effect kind
    /// </summary>
    public BuqiTrainingEffectKind EffectKind;

    /// <summary>
    /// amount
    /// </summary>
    public int Amount;

    /// <summary>
    /// duration
    /// </summary>
    public int Duration;

    /// <summary>
    /// run cap
    /// </summary>
    public int MaxPerRun;

    /// <summary>
    /// summary
    /// </summary>
    public string Summary;

    /// <summary>
    /// summary localization key
    /// </summary>
    public string SummaryLocalizationKey;

}
}

