
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiEvent :  Luban.EditorBeanBase 
{
    public DRBuqiEvent()
    {
            EventId = "";
            DisplayName = "";
            LocalizationKey = "";
            RequiredFlags = new System.Collections.Generic.List<string>();
            ForbiddenFlags = new System.Collections.Generic.List<string>();
            RevisitEventId = "";
            OptionIds = new System.Collections.Generic.List<string>();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["EventId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EventId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MinDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MinDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Weight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Weight = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RequiredFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } RequiredFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  RequiredFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["ForbiddenFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ForbiddenFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  ForbiddenFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["RevisitEventId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  RevisitEventId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RevisitDelayDays"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  RevisitDelayDays = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DayNineResolution"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsBoolean) { throw new SerializationException(); }  DayNineResolution = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["OptionIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } OptionIds = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  OptionIds.Add(__v0); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (EventId == null) { throw new System.ArgumentNullException(); }
            _json["EventId"] = new JSONString(EventId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["MinDay"] = new JSONNumber(MinDay);
        }
        {
            _json["MaxDay"] = new JSONNumber(MaxDay);
        }
        {
            _json["Weight"] = new JSONNumber(Weight);
        }
        {

            if (RequiredFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["RequiredFlags"] = __cjson0; foreach(var _e0 in RequiredFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (ForbiddenFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ForbiddenFlags"] = __cjson0; foreach(var _e0 in ForbiddenFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (RevisitEventId == null) { throw new System.ArgumentNullException(); }
            _json["RevisitEventId"] = new JSONString(RevisitEventId);
        }
        {
            _json["RevisitDelayDays"] = new JSONNumber(RevisitDelayDays);
        }
        {
            _json["DayNineResolution"] = new JSONBool(DayNineResolution);
        }
        {

            if (OptionIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["OptionIds"] = __cjson0; foreach(var _e0 in OptionIds) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
    }

    public static DRBuqiEvent LoadJsonDRBuqiEvent(JSONNode _json)
    {
        DRBuqiEvent obj = new DRBuqiEvent();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiEvent(DRBuqiEvent _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// event id
    /// </summary>
    public string EventId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// localization key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// minimum day
    /// </summary>
    public int MinDay;

    /// <summary>
    /// maximum day
    /// </summary>
    public int MaxDay;

    /// <summary>
    /// selection weight
    /// </summary>
    public int Weight;

    /// <summary>
    /// required run flags
    /// </summary>
    public System.Collections.Generic.List<string> RequiredFlags;

    /// <summary>
    /// forbidden run flags
    /// </summary>
    public System.Collections.Generic.List<string> ForbiddenFlags;

    /// <summary>
    /// cross-day revisit event
    /// </summary>
    public string RevisitEventId;

    /// <summary>
    /// revisit delay
    /// </summary>
    public int RevisitDelayDays;

    /// <summary>
    /// day nine resolution
    /// </summary>
    public bool DayNineResolution;

    /// <summary>
    /// exactly three option ids
    /// </summary>
    public System.Collections.Generic.List<string> OptionIds;

}
}

