
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiGlobal :  Luban.EditorBeanBase 
{
    public DRBuqiGlobal()
    {
            ContentVersion = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["ContentVersion"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ContentVersion = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InitialExecution"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  InitialExecution = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BufferCap"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BufferCap = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["NoiseThreshold"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  NoiseThreshold = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["NoiseIncidentDamage"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  NoiseIncidentDamage = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BoardSlotCount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BoardSlotCount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["StormStartTicks"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  StormStartTicks = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["StormBaseDamage"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  StormBaseDamage = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["StormRampDamage"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  StormRampDamage = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxTickEvents"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxTickEvents = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxItemEventsPerTick"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxItemEventsPerTick = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxChainDepth"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxChainDepth = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxRepeatedReasonPerTick"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxRepeatedReasonPerTick = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DailyEconomyProcCap"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  DailyEconomyProcCap = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (ContentVersion == null) { throw new System.ArgumentNullException(); }
            _json["ContentVersion"] = new JSONString(ContentVersion);
        }
        {
            _json["InitialExecution"] = new JSONNumber(InitialExecution);
        }
        {
            _json["BufferCap"] = new JSONNumber(BufferCap);
        }
        {
            _json["NoiseThreshold"] = new JSONNumber(NoiseThreshold);
        }
        {
            _json["NoiseIncidentDamage"] = new JSONNumber(NoiseIncidentDamage);
        }
        {
            _json["BoardSlotCount"] = new JSONNumber(BoardSlotCount);
        }
        {
            _json["StormStartTicks"] = new JSONNumber(StormStartTicks);
        }
        {
            _json["StormBaseDamage"] = new JSONNumber(StormBaseDamage);
        }
        {
            _json["StormRampDamage"] = new JSONNumber(StormRampDamage);
        }
        {
            _json["MaxTickEvents"] = new JSONNumber(MaxTickEvents);
        }
        {
            _json["MaxItemEventsPerTick"] = new JSONNumber(MaxItemEventsPerTick);
        }
        {
            _json["MaxChainDepth"] = new JSONNumber(MaxChainDepth);
        }
        {
            _json["MaxRepeatedReasonPerTick"] = new JSONNumber(MaxRepeatedReasonPerTick);
        }
        {
            _json["DailyEconomyProcCap"] = new JSONNumber(DailyEconomyProcCap);
        }
    }

    public static DRBuqiGlobal LoadJsonDRBuqiGlobal(JSONNode _json)
    {
        DRBuqiGlobal obj = new DRBuqiGlobal();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiGlobal(DRBuqiGlobal _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// content version
    /// </summary>
    public string ContentVersion;

    /// <summary>
    /// initial execution
    /// </summary>
    public int InitialExecution;

    /// <summary>
    /// buffer cap
    /// </summary>
    public int BufferCap;

    /// <summary>
    /// noise threshold
    /// </summary>
    public int NoiseThreshold;

    /// <summary>
    /// noise incident damage
    /// </summary>
    public int NoiseIncidentDamage;

    /// <summary>
    /// board slots
    /// </summary>
    public int BoardSlotCount;

    /// <summary>
    /// storm start ticks
    /// </summary>
    public int StormStartTicks;

    /// <summary>
    /// storm base true damage
    /// </summary>
    public int StormBaseDamage;

    /// <summary>
    /// storm true damage gained per tick
    /// </summary>
    public int StormRampDamage;

    /// <summary>
    /// max tick events
    /// </summary>
    public int MaxTickEvents;

    /// <summary>
    /// max item events per tick
    /// </summary>
    public int MaxItemEventsPerTick;

    /// <summary>
    /// maximum trigger chain depth
    /// </summary>
    public int MaxChainDepth;

    /// <summary>
    /// maximum repeated reason code per tick
    /// </summary>
    public int MaxRepeatedReasonPerTick;

    /// <summary>
    /// maximum economy item proc per day
    /// </summary>
    public int DailyEconomyProcCap;

}
}

