
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiEventOption :  Luban.EditorBeanBase 
{
    public DRBuqiEventOption()
    {
            OptionId = "";
            EventId = "";
            DisplayName = "";
            LocalizationKey = "";
            ConditionKind = BuqiEventConditionKind.None;
            ConditionValue = "";
            RequiredFlags = new System.Collections.Generic.List<string>();
            ForbiddenFlags = new System.Collections.Generic.List<string>();
            Costs = new System.Collections.Generic.List<BuqiEventCostConfig>();
            Outcomes = new System.Collections.Generic.List<BuqiEventOutcomeConfig>();
            SetFlags = new System.Collections.Generic.List<string>();
            ClearFlags = new System.Collections.Generic.List<string>();
            FollowUpEventId = "";
            Summary = "";
            SummaryLocalizationKey = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["OptionId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  OptionId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["EventId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EventId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Order"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Order = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ConditionKind"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { ConditionKind = (BuqiEventConditionKind)System.Enum.Parse(typeof(BuqiEventConditionKind), _fieldJson); } else if(_fieldJson.IsNumber) { ConditionKind = (BuqiEventConditionKind)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["ConditionValue"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  ConditionValue = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RequiredFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } RequiredFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  RequiredFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["ForbiddenFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ForbiddenFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  ForbiddenFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Costs"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Costs = new System.Collections.Generic.List<BuqiEventCostConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiEventCostConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiEventCostConfig.LoadJsonBuqiEventCostConfig(__e0);  Costs.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Outcomes"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Outcomes = new System.Collections.Generic.List<BuqiEventOutcomeConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiEventOutcomeConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiEventOutcomeConfig.LoadJsonBuqiEventOutcomeConfig(__e0);  Outcomes.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["SetFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } SetFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  SetFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["ClearFlags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } ClearFlags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  ClearFlags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["FollowUpEventId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  FollowUpEventId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["FollowUpDelayDays"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  FollowUpDelayDays = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Summary"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Summary = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SummaryLocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  SummaryLocalizationKey = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (OptionId == null) { throw new System.ArgumentNullException(); }
            _json["OptionId"] = new JSONString(OptionId);
        }
        {

            if (EventId == null) { throw new System.ArgumentNullException(); }
            _json["EventId"] = new JSONString(EventId);
        }
        {
            _json["Order"] = new JSONNumber(Order);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["ConditionKind"] = new JSONNumber((int)ConditionKind);
        }
        {

            if (ConditionValue == null) { throw new System.ArgumentNullException(); }
            _json["ConditionValue"] = new JSONString(ConditionValue);
        }
        {

            if (RequiredFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["RequiredFlags"] = __cjson0; foreach(var _e0 in RequiredFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (ForbiddenFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ForbiddenFlags"] = __cjson0; foreach(var _e0 in ForbiddenFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (Costs == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Costs"] = __cjson0; foreach(var _e0 in Costs) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiEventCostConfig.SaveJsonBuqiEventCostConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {

            if (Outcomes == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Outcomes"] = __cjson0; foreach(var _e0 in Outcomes) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiEventOutcomeConfig.SaveJsonBuqiEventOutcomeConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {

            if (SetFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["SetFlags"] = __cjson0; foreach(var _e0 in SetFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (ClearFlags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["ClearFlags"] = __cjson0; foreach(var _e0 in ClearFlags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (FollowUpEventId == null) { throw new System.ArgumentNullException(); }
            _json["FollowUpEventId"] = new JSONString(FollowUpEventId);
        }
        {
            _json["FollowUpDelayDays"] = new JSONNumber(FollowUpDelayDays);
        }
        {

            if (Summary == null) { throw new System.ArgumentNullException(); }
            _json["Summary"] = new JSONString(Summary);
        }
        {

            if (SummaryLocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["SummaryLocalizationKey"] = new JSONString(SummaryLocalizationKey);
        }
    }

    public static DRBuqiEventOption LoadJsonDRBuqiEventOption(JSONNode _json)
    {
        DRBuqiEventOption obj = new DRBuqiEventOption();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiEventOption(DRBuqiEventOption _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// option id
    /// </summary>
    public string OptionId;

    /// <summary>
    /// event id
    /// </summary>
    public string EventId;

    /// <summary>
    /// display order
    /// </summary>
    public int Order;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// localization key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// condition kind
    /// </summary>
    public BuqiEventConditionKind ConditionKind;

    /// <summary>
    /// condition value
    /// </summary>
    public string ConditionValue;

    /// <summary>
    /// required flags
    /// </summary>
    public System.Collections.Generic.List<string> RequiredFlags;

    /// <summary>
    /// forbidden flags
    /// </summary>
    public System.Collections.Generic.List<string> ForbiddenFlags;

    /// <summary>
    /// cost list
    /// </summary>
    public System.Collections.Generic.List<BuqiEventCostConfig> Costs;

    /// <summary>
    /// outcome list
    /// </summary>
    public System.Collections.Generic.List<BuqiEventOutcomeConfig> Outcomes;

    /// <summary>
    /// flags set
    /// </summary>
    public System.Collections.Generic.List<string> SetFlags;

    /// <summary>
    /// flags cleared
    /// </summary>
    public System.Collections.Generic.List<string> ClearFlags;

    /// <summary>
    /// follow-up event
    /// </summary>
    public string FollowUpEventId;

    /// <summary>
    /// follow-up delay
    /// </summary>
    public int FollowUpDelayDays;

    /// <summary>
    /// visible summary
    /// </summary>
    public string Summary;

    /// <summary>
    /// summary localization key
    /// </summary>
    public string SummaryLocalizationKey;

}
}

