
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiRefinement :  Luban.EditorBeanBase 
{
    public DRBuqiRefinement()
    {
            RefinementId = "";
            DisplayName = "";
            Summary = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["RefinementId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  RefinementId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Summary"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Summary = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (RefinementId == null) { throw new System.ArgumentNullException(); }
            _json["RefinementId"] = new JSONString(RefinementId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (Summary == null) { throw new System.ArgumentNullException(); }
            _json["Summary"] = new JSONString(Summary);
        }
    }

    public static DRBuqiRefinement LoadJsonDRBuqiRefinement(JSONNode _json)
    {
        DRBuqiRefinement obj = new DRBuqiRefinement();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiRefinement(DRBuqiRefinement _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// refinement id
    /// </summary>
    public string RefinementId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// summary
    /// </summary>
    public string Summary;

}
}

