
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiMerchant :  Luban.EditorBeanBase 
{
    public DRBuqiMerchant()
    {
            MerchantId = "";
            DisplayName = "";
            LocalizationKey = "";
            PoolItemIds = new System.Collections.Generic.List<string>();
            Slots = new System.Collections.Generic.List<BuqiMerchantSlotConfig>();
            Specialty = BuqiMerchantSpecialty.General;
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["MerchantId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  MerchantId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MinDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MinDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MaxDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MaxDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Weight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Weight = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["PoolItemIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } PoolItemIds = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  PoolItemIds.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Slots"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Slots = new System.Collections.Generic.List<BuqiMerchantSlotConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiMerchantSlotConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiMerchantSlotConfig.LoadJsonBuqiMerchantSlotConfig(__e0);  Slots.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Specialty"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Specialty = (BuqiMerchantSpecialty)System.Enum.Parse(typeof(BuqiMerchantSpecialty), _fieldJson); } else if(_fieldJson.IsNumber) { Specialty = (BuqiMerchantSpecialty)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (MerchantId == null) { throw new System.ArgumentNullException(); }
            _json["MerchantId"] = new JSONString(MerchantId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["MinDay"] = new JSONNumber(MinDay);
        }
        {
            _json["MaxDay"] = new JSONNumber(MaxDay);
        }
        {
            _json["Weight"] = new JSONNumber(Weight);
        }
        {

            if (PoolItemIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["PoolItemIds"] = __cjson0; foreach(var _e0 in PoolItemIds) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (Slots == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Slots"] = __cjson0; foreach(var _e0 in Slots) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiMerchantSlotConfig.SaveJsonBuqiMerchantSlotConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {
            _json["Specialty"] = new JSONNumber((int)Specialty);
        }
    }

    public static DRBuqiMerchant LoadJsonDRBuqiMerchant(JSONNode _json)
    {
        DRBuqiMerchant obj = new DRBuqiMerchant();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiMerchant(DRBuqiMerchant _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// merchant id
    /// </summary>
    public string MerchantId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// localization key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// minimum day
    /// </summary>
    public int MinDay;

    /// <summary>
    /// maximum day
    /// </summary>
    public int MaxDay;

    /// <summary>
    /// selection weight
    /// </summary>
    public int Weight;

    /// <summary>
    /// constrained item pool
    /// </summary>
    public System.Collections.Generic.List<string> PoolItemIds;

    /// <summary>
    /// offer slot constraints
    /// </summary>
    public System.Collections.Generic.List<BuqiMerchantSlotConfig> Slots;

    /// <summary>
    /// formal merchant supply specialty
    /// </summary>
    public BuqiMerchantSpecialty Specialty;

}
}

