
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace Game.Hot.Editor
{

public sealed class DRBuqiItem :  Luban.EditorBeanBase 
{
    public DRBuqiItem()
    {
            DefinitionId = "";
            DisplayName = "";
            DesignNote = "";
            EffectDescription = "";
            LocalizationKey = "";
            Size = BuqiSize.S;
            ArchetypeId = BuqiBuild.fast;
            Role = "";
            PositionHint = "";
            Tags = new System.Collections.Generic.List<string>();
            Effects = new System.Collections.Generic.List<BuqiEffectConfig>();
            RunEffects = new System.Collections.Generic.List<BuqiRunEffectConfig>();
            UpgradeSummary = "";
            UpgradeLocalizationKey = "";
            LinkIds = new System.Collections.Generic.List<string>();
            Category = BuqiItemCategory.Unknown;
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["DefinitionId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DefinitionId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DisplayName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DisplayName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["DesignNote"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  DesignNote = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["EffectDescription"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  EffectDescription = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  LocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Size"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Size = (BuqiSize)System.Enum.Parse(typeof(BuqiSize), _fieldJson); } else if(_fieldJson.IsNumber) { Size = (BuqiSize)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["BasePrice"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BasePrice = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ImprovedUpgradeCost"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  ImprovedUpgradeCost = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["FixedUpgradeCost"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  FixedUpgradeCost = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["RefinementCost"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  RefinementCost = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["BaseCooldownTicks"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  BaseCooldownTicks = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ArchetypeId"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { ArchetypeId = (BuqiBuild)System.Enum.Parse(typeof(BuqiBuild), _fieldJson); } else if(_fieldJson.IsNumber) { ArchetypeId = (BuqiBuild)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
        { 
            var _fieldJson = _json["Role"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Role = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["UnlockDay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  UnlockDay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["PositionHint"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  PositionHint = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Tags"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  Tags.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Effects"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<BuqiEffectConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiEffectConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiEffectConfig.LoadJsonBuqiEffectConfig(__e0);  Effects.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["RunEffects"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } RunEffects = new System.Collections.Generic.List<BuqiRunEffectConfig>(); foreach(JSONNode __e0 in _fieldJson.Children) { BuqiRunEffectConfig __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = BuqiRunEffectConfig.LoadJsonBuqiRunEffectConfig(__e0);  RunEffects.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["UpgradeSummary"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  UpgradeSummary = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["UpgradeLocalizationKey"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  UpgradeLocalizationKey = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["LinkIds"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } LinkIds = new System.Collections.Generic.List<string>(); foreach(JSONNode __e0 in _fieldJson.Children) { string __v0;  if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0;  LinkIds.Add(__v0); }  
            }
        }
        
        { 
            var _fieldJson = _json["Category"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { Category = (BuqiItemCategory)System.Enum.Parse(typeof(BuqiItemCategory), _fieldJson); } else if(_fieldJson.IsNumber) { Category = (BuqiItemCategory)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {

            if (DefinitionId == null) { throw new System.ArgumentNullException(); }
            _json["DefinitionId"] = new JSONString(DefinitionId);
        }
        {

            if (DisplayName == null) { throw new System.ArgumentNullException(); }
            _json["DisplayName"] = new JSONString(DisplayName);
        }
        {

            if (DesignNote == null) { throw new System.ArgumentNullException(); }
            _json["DesignNote"] = new JSONString(DesignNote);
        }
        {

            if (EffectDescription == null) { throw new System.ArgumentNullException(); }
            _json["EffectDescription"] = new JSONString(EffectDescription);
        }
        {

            if (LocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["LocalizationKey"] = new JSONString(LocalizationKey);
        }
        {
            _json["Size"] = new JSONNumber((int)Size);
        }
        {
            _json["BasePrice"] = new JSONNumber(BasePrice);
        }
        {
            _json["ImprovedUpgradeCost"] = new JSONNumber(ImprovedUpgradeCost);
        }
        {
            _json["FixedUpgradeCost"] = new JSONNumber(FixedUpgradeCost);
        }
        {
            _json["RefinementCost"] = new JSONNumber(RefinementCost);
        }
        {
            _json["BaseCooldownTicks"] = new JSONNumber(BaseCooldownTicks);
        }
        {
            _json["ArchetypeId"] = new JSONNumber((int)ArchetypeId);
        }
        {

            if (Role == null) { throw new System.ArgumentNullException(); }
            _json["Role"] = new JSONString(Role);
        }
        {
            _json["UnlockDay"] = new JSONNumber(UnlockDay);
        }
        {

            if (PositionHint == null) { throw new System.ArgumentNullException(); }
            _json["PositionHint"] = new JSONString(PositionHint);
        }
        {

            if (Tags == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Tags"] = __cjson0; foreach(var _e0 in Tags) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {

            if (Effects == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Effects"] = __cjson0; foreach(var _e0 in Effects) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiEffectConfig.SaveJsonBuqiEffectConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {

            if (RunEffects == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["RunEffects"] = __cjson0; foreach(var _e0 in RunEffects) { JSONNode __v0; { var __bjson1 = new JSONObject();  __v0 = __bjson1; BuqiRunEffectConfig.SaveJsonBuqiRunEffectConfig(_e0, __bjson1); } __cjson0.Add(__v0); } }
        }
        {

            if (UpgradeSummary == null) { throw new System.ArgumentNullException(); }
            _json["UpgradeSummary"] = new JSONString(UpgradeSummary);
        }
        {

            if (UpgradeLocalizationKey == null) { throw new System.ArgumentNullException(); }
            _json["UpgradeLocalizationKey"] = new JSONString(UpgradeLocalizationKey);
        }
        {

            if (LinkIds == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["LinkIds"] = __cjson0; foreach(var _e0 in LinkIds) { JSONNode __v0; __v0 = new JSONString(_e0); __cjson0.Add(__v0); } }
        }
        {
            _json["Category"] = new JSONNumber((int)Category);
        }
    }

    public static DRBuqiItem LoadJsonDRBuqiItem(JSONNode _json)
    {
        DRBuqiItem obj = new DRBuqiItem();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRBuqiItem(DRBuqiItem _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    /// <summary>
    /// item id
    /// </summary>
    public string DefinitionId;

    /// <summary>
    /// display name
    /// </summary>
    public string DisplayName;

    /// <summary>
    /// planner-only Chinese usage note
    /// </summary>
    public string DesignNote;

    /// <summary>
    /// formal in-game effect description
    /// </summary>
    public string EffectDescription;

    /// <summary>
    /// localized item name key
    /// </summary>
    public string LocalizationKey;

    /// <summary>
    /// size
    /// </summary>
    public BuqiSize Size;

    /// <summary>
    /// price
    /// </summary>
    public int BasePrice;

    /// <summary>
    /// improved upgrade cost
    /// </summary>
    public int ImprovedUpgradeCost;

    /// <summary>
    /// fixed upgrade cost
    /// </summary>
    public int FixedUpgradeCost;

    /// <summary>
    /// refinement cost
    /// </summary>
    public int RefinementCost;

    /// <summary>
    /// cooldown ticks
    /// </summary>
    public int BaseCooldownTicks;

    /// <summary>
    /// build
    /// </summary>
    public BuqiBuild ArchetypeId;

    /// <summary>
    /// supply role
    /// </summary>
    public string Role;

    /// <summary>
    /// unlock day
    /// </summary>
    public int UnlockDay;

    /// <summary>
    /// recommended board position
    /// </summary>
    public string PositionHint;

    /// <summary>
    /// tags
    /// </summary>
    public System.Collections.Generic.List<string> Tags;

    /// <summary>
    /// battle effect list
    /// </summary>
    public System.Collections.Generic.List<BuqiEffectConfig> Effects;

    /// <summary>
    /// run-layer effect list
    /// </summary>
    public System.Collections.Generic.List<BuqiRunEffectConfig> RunEffects;

    /// <summary>
    /// quality upgrade summary
    /// </summary>
    public string UpgradeSummary;

    /// <summary>
    /// localized upgrade summary key
    /// </summary>
    public string UpgradeLocalizationKey;

    /// <summary>
    /// linked item ids
    /// </summary>
    public System.Collections.Generic.List<string> LinkIds;

    /// <summary>
    /// formal weapon or non-weapon supply classification
    /// </summary>
    public BuqiItemCategory Category;

}
}

